// Booking Management feature specific translations
export const usageTrackingTranslate = {
  en: {
    translation: {
      // Usage Tracking Component
      "usageTracking.title": "Vehicle Maintenance Management",
      "usageTracking.subtitle": "Track vehicle status",
      "usageTracking.searchPlaceholder": "Search by car name, license plate or ID",
      "usageTracking.allBrands": "All Brands",
      "usageTracking.selectBrandFirst": "Select brand first",
      "usageTracking.allModels": "All Models",
      "usageTracking.allStatuses": "All Statuses",
      "usageTracking.allParkLots": "All Park Lots",
      "usageTracking.showingResults": "Showing {{filtered}} of {{total}} vehicles",
      "usageTracking.carInfo": "Car Information",
      "usageTracking.parkLot": "Park Lot",
      "usageTracking.rentals": "Rentals",
      "usageTracking.daysRented": "Days Rented",
      "usageTracking.balance": "Balance",
      "usageTracking.walletBalance": "wallet balance",
      "usageTracking.status": "Status",
      "usageTracking.actions": "Actions",
      "usageTracking.totalBookings": "Total completed bookings",
      "usageTracking.totalBookingsModal": "Total bookings",
      "usageTracking.days": "days",
      "usageTracking.viewDetails": "View Details",
      "usageTracking.schedule": "Schedule",
      "usageTracking.noCarsFound": "No cars found",
      "usageTracking.loadingCars": "Loading car data...",
      "usageTracking.errorLoadingCars": "Unable to load car data",
      "usageTracking.cannotIdentifyUser": "Cannot identify current user. Please log in again.",
      "usageTracking.available": "Available",
      "usageTracking.reserved": "Reserved",
      "usageTracking.maintenance": "Maintenance",
      "usageTracking.pending": "Pending",
      "usageTracking.denied": "Denied",
      "usageTracking.unavailable": "Unavailable",
      "usageTracking.unknown": "Unknown",
      "usageTracking.seats": "seats",
      "usageTracking.topUp": "Top Up",
      "usageTracking.hasBalance": "Has Balance",
      "usageTracking.viewTravelLog": "Travel Log",

      // Usage Details Modal
      "usageTracking.usageDetails": "Car Details",
      "usageTracking.carName": "Car Name",
      "usageTracking.licensePlate": "License Plate",
      "usageTracking.totalRentals": "Total Rentals",
      "usageTracking.totalRentalsModal": "Total Rentals (Booking Completed)",
      "usageTracking.totalDaysRented": "Total Days Rented",
      "usageTracking.currentStatus": "Current Status",
      "usageTracking.scheduleMaintenance": "Schedule Maintenance",

      // Payment Chart
      "usageTracking.paymentHistory": "Payment History",
      "usageTracking.last7Days": "7 Days",
      "usageTracking.last7Months": "7 Months",
      "usageTracking.last7Years": "7 Years",
      "usageTracking.totalRevenue": "Total Revenue",
      "usageTracking.totalRentalModal": "Number of Payment",
      "usageTracking.totalPayments": "Total Payments",
      "usageTracking.revenue": "Revenue",
      "usageTracking.payments": "payments",
      "usageTracking.loadingPayments": "Loading payments...",
      "usageTracking.errorLoadingPayments": "Error loading payments",
      "usageTracking.noPaymentsFound": "No payments found",
      "usageTracking.noPaymentData": "No Payment Data",
      "usageTracking.noPaymentsYet": "No payments have been made for this car yet",

      // Booking Trend Chart
      "usageTracking.bookingTrend": "Booking Trend",
      "usageTracking.bookings": "Bookings",
      "usageTracking.pending": "Pending",
      "usageTracking.confirmed": "Confirmed",
      "usageTracking.inProgress": "In Progress",
      "usageTracking.completed": "Completed",
      "usageTracking.cancelled": "Cancelled",
      "usageTracking.trend": "Trend",
      "usageTracking.increasing": "Increasing",
      "usageTracking.decreasing": "Decreasing",
      "usageTracking.change": "Change",
      "usageTracking.confirmedAndCompleted": "Confirmed & Completed",
      "usageTracking.statusBreakdown": "Status Breakdown",
      "usageTracking.loadingBookings": "Loading bookings...",
      "usageTracking.errorLoadingBookings": "Error loading bookings",
      "usageTracking.noBookingsFound": "No bookings found",
      "usageTracking.noBookingData": "No Booking Data",
      "usageTracking.noBookingsYet": "No bookings have been made for this car yet",

      // Travel Log Modal
      "travelLog.title": "Travel Log",
      "travelLog.loading": "Loading travel logs...",
      "travelLog.errorLoading": "Failed to load travel logs",
      "travelLog.noLogs": "No travel logs found for this car",
      "travelLog.totalTrips": "Total Trips",
      "travelLog.totalCharges": "Total Charges",
      "travelLog.uniqueTollBooths": "Unique Toll Booths",
      "travelLog.travelDate": "Travel Date",
      "travelLog.bookingNumber": "Booking Number",
      "travelLog.tollBoothId": "Toll Booth",
      "travelLog.chargeAmount": "Charge Amount",

      // Top Up Modal
      "topUpModal.title": "Top Up Car Wallet",
      "topUpModal.car": "Car",
      "topUpModal.amountLabel": "Amount",
      "topUpModal.required": "*",
      "topUpModal.minimumAmount": "Minimum amount: 10,000 VND",
      "topUpModal.invalidAmount": "Please enter a valid amount",
      "topUpModal.minimumAmountError": "Minimum amount is 10,000 VND",
      "topUpModal.successMessage": "Payment request created successfully!",
      "topUpModal.paymentRedirectMessage": "You will be redirected to PayOS to complete the payment.",
      "topUpModal.noPaymentUrlError": "Payment URL not received. Please try again.",
      "topUpModal.topUpError": "Failed to process top-up. Please try again.",
      "topUpModal.cancel": "Cancel",
      "topUpModal.topUpButton": "Top Up",
      "topUpModal.processing": "Processing...",
    }
  },
  vi: {
    translation: {
      // Usage Tracking Component
      "usageTracking.title": "Quản lý bảo dưỡng xe",
      "usageTracking.subtitle": "theo dõi tình trạng xe",
      "usageTracking.searchPlaceholder": "Tìm kiếm theo tên xe, biển số hoặc ID",
      "usageTracking.allBrands": "Tất cả thương hiệu",
      "usageTracking.selectBrandFirst": "Chọn thương hiệu trước",
      "usageTracking.allModels": "Tất cả mẫu xe",
      "usageTracking.allStatuses": "Tất cả trạng thái",
      "usageTracking.allParkLots": "Tất cả bãi đỗ xe",
      "usageTracking.showingResults": "Hiển thị {{filtered}} trong tổng số {{total}} xe",
      "usageTracking.carInfo": "Thông tin xe",
      "usageTracking.parkLot": "Bãi đỗ xe",
      "usageTracking.rentals": "Lượt thuê",
      "usageTracking.daysRented": "Số ngày thuê",
      "usageTracking.balance": "Số dư",
      "usageTracking.walletBalance": "số dư ví",
      "usageTracking.status": "Trạng thái",
      "usageTracking.actions": "Thao tác",
      "usageTracking.totalBookings": "Tổng đặt xe",
      "usageTracking.days": "ngày",
      "usageTracking.viewDetails": "Xem chi tiết",
      "usageTracking.schedule": "Lên lịch",
      "usageTracking.noCarsFound": "Không tìm thấy xe nào",
      "usageTracking.loadingCars": "Đang tải dữ liệu xe...",
      "usageTracking.errorLoadingCars": "Không thể tải dữ liệu xe",
      "usageTracking.cannotIdentifyUser": "Không thể xác định người dùng hiện tại. Vui lòng đăng nhập lại.",
      "usageTracking.available": "Có sẵn",
      "usageTracking.reserved": "Đã đặt",
      "usageTracking.maintenance": "Bảo dưỡng",
      "usageTracking.pending": "Chờ nộp giấy tờ",
      "usageTracking.denied": "Từ chối",
      "usageTracking.unavailable": "Không khả dụng",
      "usageTracking.unknown": "không rõ",
      "usageTracking.seats": "chỗ",
      "usageTracking.topUp": "Nạp tiền",
      "usageTracking.hasBalance": "Có số dư",
      "usageTracking.viewTravelLog": "Lịch sử di chuyển",

      // Usage Details Modal
      "usageTracking.usageDetails": "Chi tiết sử dụng & Quãng đường",
      "usageTracking.carName": "Tên xe",
      "usageTracking.licensePlate": "Biển số",
      "usageTracking.totalRentals": "Tổng lượt thuê",
      "usageTracking.totalDaysRented": "Tổng số ngày thuê",
      "usageTracking.currentStatus": "Trạng thái hiện tại",
      "usageTracking.scheduleMaintenance": "Lên lịch bảo dưỡng",

      // Payment Chart
      "usageTracking.paymentHistory": "Lịch sử thanh toán",
      "usageTracking.last7Days": "7 Ngày",
      "usageTracking.last7Months": "7 Tháng",
      "usageTracking.last7Years": "7 Năm",
      "usageTracking.totalRevenue": "Tổng doanh thu",
      "usageTracking.totalPayments": "Tổng thanh toán",
      "usageTracking.revenue": "Doanh thu",
      "usageTracking.payments": "thanh toán",
      "usageTracking.loadingPayments": "Đang tải thanh toán...",
      "usageTracking.errorLoadingPayments": "Lỗi tải thanh toán",
      "usageTracking.noPaymentsFound": "Không tìm thấy thanh toán",
      "usageTracking.noPaymentData": "Không có dữ liệu thanh toán",
      "usageTracking.noPaymentsYet": "Chưa có thanh toán nào cho xe này",

      // Booking Trend Chart
      "usageTracking.bookingTrend": "Xu hướng đặt xe",
      "usageTracking.bookings": "Đặt xe",
      "usageTracking.pending": "Chờ xử lý",
      "usageTracking.confirmed": "Đã xác nhận",
      "usageTracking.inProgress": "Đang thực hiện",
      "usageTracking.completed": "Hoàn thành",
      "usageTracking.cancelled": "Đã hủy",
      "usageTracking.trend": "Xu hướng",
      "usageTracking.increasing": "Tăng",
      "usageTracking.decreasing": "Giảm",
      "usageTracking.change": "Thay đổi",
      "usageTracking.confirmedAndCompleted": "Đã xác nhận & Hoàn thành",
      "usageTracking.statusBreakdown": "Phân tích trạng thái",
      "usageTracking.loadingBookings": "Đang tải đặt xe...",
      "usageTracking.errorLoadingBookings": "Lỗi tải đặt xe",
      "usageTracking.noBookingsFound": "Không tìm thấy đặt xe",
      "usageTracking.noBookingData": "Không có dữ liệu đặt xe",
      "usageTracking.noBookingsYet": "Chưa có đặt xe nào cho xe này",

      // Travel Log Modal
      "travelLog.title": "Lịch sử di chuyển",
      "travelLog.loading": "Đang tải lịch sử di chuyển...",
      "travelLog.errorLoading": "Không thể tải lịch sử di chuyển",
      "travelLog.noLogs": "Không có lịch sử di chuyển cho xe này",
      "travelLog.totalTrips": "Tổng số chuyến",
      "travelLog.totalCharges": "Tổng phí",
      "travelLog.uniqueTollBooths": "Số trạm thu phí",
      "travelLog.travelDate": "Ngày di chuyển",
      "travelLog.bookingNumber": "Mã đặt xe",
      "travelLog.tollBoothId": "Trạm thu phí",
      "travelLog.chargeAmount": "Số tiền",

      // Top Up Modal
      "topUpModal.title": "Nạp tiền vào ví xe",
      "topUpModal.car": "Xe",
      "topUpModal.amountLabel": "Số tiền",
      "topUpModal.required": "*",
      "topUpModal.minimumAmount": "Số tiền tối thiểu: 10.000 VND",
      "topUpModal.invalidAmount": "Vui lòng nhập số tiền hợp lệ",
      "topUpModal.minimumAmountError": "Số tiền tối thiểu là 10.000 VND",
      "topUpModal.successMessage": "Tạo yêu cầu thanh toán thành công!",
      "topUpModal.paymentRedirectMessage": "Bạn sẽ được chuyển hướng đến PayOS để hoàn tất thanh toán.",
      "topUpModal.noPaymentUrlError": "Không nhận được URL thanh toán. Vui lòng thử lại.",
      "topUpModal.topUpError": "Không thể nạp tiền. Vui lòng thử lại.",
      "topUpModal.cancel": "Hủy",
      "topUpModal.topUpButton": "Nạp tiền",
      "topUpModal.processing": "Đang xử lý...",
    }
  }
};