// Booking Management feature specific translations
export const usageTrackingTranslate = {
  en: {
    translation: {
      // Usage Tracking Component
      "usageTracking.title": "Vehicle Maintenance Management",
      "usageTracking.subtitle": "Track vehicle status",
      "usageTracking.searchPlaceholder": "Search by car name, license plate or ID",
      "usageTracking.allBrands": "All Brands",
      "usageTracking.selectBrandFirst": "Select brand first",
      "usageTracking.allModels": "All Models",
      "usageTracking.allStatuses": "All Statuses",
      "usageTracking.allParkLots": "All Park Lots",
      "usageTracking.showingResults": "Showing {{filtered}} of {{total}} vehicles",
      "usageTracking.carInfo": "Car Information",
      "usageTracking.parkLot": "Park Lot",
      "usageTracking.rentals": "Rentals",
      "usageTracking.daysRented": "Days Rented",
      "usageTracking.balance": "Balance",
      "usageTracking.walletBalance": "wallet balance",
      "usageTracking.status": "Status",
      "usageTracking.actions": "Actions",
      "usageTracking.totalBookings": "Total bookings",
      "usageTracking.days": "days",
      "usageTracking.viewDetails": "View Details",
      "usageTracking.schedule": "Schedule",
      "usageTracking.noCarsFound": "No cars found",
      "usageTracking.loadingCars": "Loading car data...",
      "usageTracking.errorLoadingCars": "Unable to load car data",
      "usageTracking.cannotIdentifyUser": "Cannot identify current user. Please log in again.",
      "usageTracking.available": "Available",
      "usageTracking.reserved": "Reserved",
      "usageTracking.maintenance": "Maintenance",
      "usageTracking.pending": "Pending",
      "usageTracking.denied": "Denied",
      "usageTracking.unavailable": "Unavailable",
      "usageTracking.unknown": "Unknown",
      "usageTracking.seats": "seats",
      "usageTracking.topUp": "Top Up",
      "usageTracking.hasBalance": "Has Balance",

      // Top Up Modal
      "topUpModal.title": "Top Up Car Wallet",
      "topUpModal.car": "Car",
      "topUpModal.amountLabel": "Amount",
      "topUpModal.required": "*",
      "topUpModal.minimumAmount": "Minimum amount: 10,000 VND",
      "topUpModal.invalidAmount": "Please enter a valid amount",
      "topUpModal.minimumAmountError": "Minimum amount is 10,000 VND",
      "topUpModal.successMessage": "Payment request created successfully!",
      "topUpModal.paymentRedirectMessage": "You will be redirected to PayOS to complete the payment.",
      "topUpModal.noPaymentUrlError": "Payment URL not received. Please try again.",
      "topUpModal.topUpError": "Failed to process top-up. Please try again.",
      "topUpModal.cancel": "Cancel",
      "topUpModal.topUpButton": "Top Up",
      "topUpModal.processing": "Processing...",
    }
  },
  vi: {
    translation: {
      // Usage Tracking Component
      "usageTracking.title": "Quản lý bảo dưỡng xe",
      "usageTracking.subtitle": "theo dõi tình trạng xe",
      "usageTracking.searchPlaceholder": "Tìm kiếm theo tên xe, biển số hoặc ID",
      "usageTracking.allBrands": "Tất cả thương hiệu",
      "usageTracking.selectBrandFirst": "Chọn thương hiệu trước",
      "usageTracking.allModels": "Tất cả mẫu xe",
      "usageTracking.allStatuses": "Tất cả trạng thái",
      "usageTracking.allParkLots": "Tất cả bãi đỗ xe",
      "usageTracking.showingResults": "Hiển thị {{filtered}} trong tổng số {{total}} xe",
      "usageTracking.carInfo": "Thông tin xe",
      "usageTracking.parkLot": "Bãi đỗ xe",
      "usageTracking.rentals": "Lượt thuê",
      "usageTracking.daysRented": "Số ngày thuê",
      "usageTracking.balance": "Số dư",
      "usageTracking.walletBalance": "số dư ví",
      "usageTracking.status": "Trạng thái",
      "usageTracking.actions": "Thao tác",
      "usageTracking.totalBookings": "Tổng đặt xe",
      "usageTracking.days": "ngày",
      "usageTracking.viewDetails": "Xem chi tiết",
      "usageTracking.schedule": "Lên lịch",
      "usageTracking.noCarsFound": "Không tìm thấy xe nào",
      "usageTracking.loadingCars": "Đang tải dữ liệu xe...",
      "usageTracking.errorLoadingCars": "Không thể tải dữ liệu xe",
      "usageTracking.cannotIdentifyUser": "Không thể xác định người dùng hiện tại. Vui lòng đăng nhập lại.",
      "usageTracking.available": "Có sẵn",
      "usageTracking.reserved": "Đã đặt",
      "usageTracking.maintenance": "Bảo dưỡng",
      "usageTracking.pending": "Chờ nộp giấy tờ",
      "usageTracking.denied": "Từ chối",
      "usageTracking.unavailable": "Không khả dụng",
      "usageTracking.unknown": "không rõ",
      "usageTracking.seats": "chỗ",
      "usageTracking.topUp": "Nạp tiền",
      "usageTracking.hasBalance": "Có số dư",

      // Top Up Modal
      "topUpModal.title": "Nạp tiền vào ví xe",
      "topUpModal.car": "Xe",
      "topUpModal.amountLabel": "Số tiền",
      "topUpModal.required": "*",
      "topUpModal.minimumAmount": "Số tiền tối thiểu: 10.000 VND",
      "topUpModal.invalidAmount": "Vui lòng nhập số tiền hợp lệ",
      "topUpModal.minimumAmountError": "Số tiền tối thiểu là 10.000 VND",
      "topUpModal.successMessage": "Tạo yêu cầu thanh toán thành công!",
      "topUpModal.paymentRedirectMessage": "Bạn sẽ được chuyển hướng đến PayOS để hoàn tất thanh toán.",
      "topUpModal.noPaymentUrlError": "Không nhận được URL thanh toán. Vui lòng thử lại.",
      "topUpModal.topUpError": "Không thể nạp tiền. Vui lòng thử lại.",
      "topUpModal.cancel": "Hủy",
      "topUpModal.topUpButton": "Nạp tiền",
      "topUpModal.processing": "Đang xử lý...",
    }
  }
};