// Owner feature specific translations
export const ownerTranslations = {
  en: {
    translation: {
      // Car Registration Documents
      "carRegisDocs.title": "Car Registration Documents",
      "carRegisDocs.subtitle": "Manage and track vehicle registration document approvals",
      "carRegisDocs.allCars": "All Cars ({{count}})",
      "carRegisDocs.pendingApproval": "Pending Approval ({{count}})",
      "carRegisDocs.approved": "Approved ({{count}})",
      "carRegisDocs.noCarsFound": "No cars found",
      "carRegisDocs.noRegisteredCars": "You haven't registered any cars yet.",
      "carRegisDocs.noPendingCars": "No cars found {{status}}.",
      "carRegisDocs.noApprovedCars": "No {{status}} cars found.",
      "carRegisDocs.noUploadCars": "No cars without uploaded documents found.",
      "carRegisDocs.noDeniedCars": "No denied cars found.",
      "carRegisDocs.pending": "pending approval",
      "carRegisDocs.licensePlate": "License Plate",
      "carRegisDocs.seats": "Seats",
      "carRegisDocs.yearOfManufacture": "Year of Manufacture",
      "carRegisDocs.fuelConsumption": "Fuel Consumption",
      "carRegisDocs.transmission": "Transmission",
      "carRegisDocs.fuelType": "Fuel Type",
      "carRegisDocs.preferredLot": "Preferred Lot",
      "carRegisDocs.uploadDocuments": "Upload Documents",
      "carRegisDocs.uploading": "Uploading...",
      "carRegisDocs.uploadSuccess": "Upload successful!",
      "carRegisDocs.statusPending": "Pending Approval",
      "carRegisDocs.statusApproved": "Approved",
      "carRegisDocs.documentsPendingApproval": "Documents are being reviewed",
      "carRegisDocs.showing": "Showing",
      "carRegisDocs.to": "to",
      "carRegisDocs.of": "of",
      "carRegisDocs.results": "results",
      "carRegisDocs.previous": "Previous",
      "carRegisDocs.next": "Next",
      "carRegisDocs.page": "Page",
      "carRegisDocs.loadingError": "Failed to load cars. Please try again.",
      "carRegisDocs.uploadError": "Failed to upload documents. Please try again.",
      "carRegisDocs.fuelConsumptionUnit": "L/100km",
      "carRegisDocs.statusNoUpload": "Not Upload Reg Doc",
      "carRegisDocs.statusDenied":"Denied",
      "carRegisDocs.noUpload": "No Upload Reg Doc ({{count}})",
      "carRegisDocs.denied":"Denied ({{count}})",
      "carRegisDocs.noDocumentsUploaded": "No documents uploaded"
    }
  },
  vi: {
    translation: {
      // Car Registration Documents
      "carRegisDocs.title": "Giấy tờ đăng ký xe",
      "carRegisDocs.subtitle": "Quản lý và theo dõi việc phê duyệt tài liệu đăng ký xe",
      "carRegisDocs.allCars": "Tất cả xe ({{count}})",
      "carRegisDocs.pendingApproval": "Chờ duyệt ({{count}})",
      "carRegisDocs.approved": "Đã duyệt ({{count}})",
      "carRegisDocs.noCarsFound": "Không tìm thấy xe nào",
      "carRegisDocs.noRegisteredCars": "Bạn chưa đăng ký xe nào.",
      "carRegisDocs.noPendingCars": "Không tìm thấy xe {{status}} nào.",
      "carRegisDocs.noApprovedCars": "Không tìm thấy xe {{status}} nào.",
      "carRegisDocs.noUploadCars": "Không tìm thấy xe nào chưa tải lên tài liệu.",
      "carRegisDocs.noDeniedCars": "Không tìm thấy xe nào bị từ chối.",
      "carRegisDocs.pending": "chờ duyệt",
      "carRegisDocs.licensePlate": "Biển số xe",
      "carRegisDocs.seats": "Số ghế",
      "carRegisDocs.yearOfManufacture": "Năm sản xuất",
      "carRegisDocs.fuelConsumption": "Mức tiêu thụ nhiên liệu",
      "carRegisDocs.transmission": "Hộp số",
      "carRegisDocs.fuelType": "Loại nhiên liệu",
      "carRegisDocs.preferredLot": "Bãi xe ưu tiên",
      "carRegisDocs.uploadDocuments": "Tải lên tài liệu",
      "carRegisDocs.uploading": "Đang tải lên...",
      "carRegisDocs.uploadSuccess": "Tải lên thành công!",
      "carRegisDocs.statusPending": "Chờ phê duyệt",
      "carRegisDocs.statusApproved": "Đã phê duyệt",
      "carRegisDocs.documentsPendingApproval": "Hồ sơ đang được phê duyệt",
      "carRegisDocs.showing": "Hiển thị",
      "carRegisDocs.to": "đến",
      "carRegisDocs.of": "trong tổng số",
      "carRegisDocs.results": "kết quả",
      "carRegisDocs.previous": "Trước",
      "carRegisDocs.next": "Tiếp",
      "carRegisDocs.page": "Trang",
      "carRegisDocs.loadingError": "Không thể tải danh sách xe. Vui lòng thử lại.",
      "carRegisDocs.uploadError": "Không thể tải tài liệu lên. Vui lòng thử lại.",
      "carRegisDocs.fuelConsumptionUnit": "L/100km",
      "carRegisDocs.statusNoUpload": "Chưa tải lên giấy tờ",
      "carRegisDocs.statusDenied": "Bị từ chối",
      "carRegisDocs.noUpload": "Chưa tải lên giấy tờ ({{count}})",
      "carRegisDocs.denied": "Bị từ chối ({{count}})",
      "carRegisDocs.noDocumentsUploaded": "Chưa tải lên tài liệu nào"
    }
  }
};