export const adminTranslate = {
  en: {
    translation: {
      // Admin - Sidebar
      mainMenu: "MAIN MENU",
      dashboard: "Dashboard",
      operationsDashboard: "Operations Dashboard",
      transactionMonitoring: "Transaction Monitoring",
      carRent: "Car Rent",
      insight: "Insight",
      reimburse: "Reimburse",
      inbox: "Inbox",
      calendar: "Calendar",
      preferences: "PREFERENCES",
      settings: "Settings",
      helpCenter: "Help & Center",
      darkMode: "Dark Mode",
      ownerPage: "Owner Page",
      staffPage: "Staff Page",
      createStaff: "Create Staff",
      
      // Admin - Create Staff
      createStaffTitle: "Create Staff Account",
      createStaffUsername: "Username",
      createStaffUsernamePlaceholder: "Enter username",
      createStaffUsernameRequired: "Username is required",
      createStaffPassword: "Password",
      createStaffPasswordPlaceholder: "Enter password",
      createStaffPasswordRequired: "Password is required",
      createStaffPasswordMinLength: "Password must be at least 6 characters",
      createStaffFullname: "Full Name",
      createStaffFullnamePlaceholder: "Enter full name",
      createStaffFullnameRequired: "Full name is required",
      createStaffEmail: "Email",
      createStaffEmailPlaceholder: "Enter email address",
      createStaffEmailRequired: "Email is required",
      createStaffEmailInvalid: "Please enter a valid email address",
      createStaffPhoneNumber: "Phone Number",
      createStaffPhoneNumberPlaceholder: "Enter phone number",
      createStaffPhoneRequired: "Phone number is required",
      createStaffPhoneInvalid: "Phone number must be 10 digits starting with 0 (e.g., 0969468855)",
      createStaffDateOfBirth: "Date of Birth",
      createStaffDateOfBirthRequired: "Date of birth is required",
      createStaffAddress: "Address",
      createStaffAddressPlaceholder: "Enter address",
      createStaffAddressRequired: "Address is required",
      createStaffGender: "Gender",
      createStaffGenderMale: "Male",
      createStaffGenderFemale: "Female",
      createStaffCreateButton: "Create Staff Account",
      createStaffCreating: "Creating...",
      createStaffSuccessMessage: "Staff account created successfully!",
      createStaffErrorMessage: "Failed to create staff account. Please try again.",
      
      // Admin - Status Overview
      statusOverview: "Booking and Car Status Overview",
      status: "Status",
      statusBookingAdmin: "Booking status",
      statusCarAdmin: "Car status",
      paid: "Paid",
      unpaid: "Unpaid",
      rented: "Rented",
      overdue: "Overdue",
      available: "Available",
      returned: "Returned",
      previous: "Previous",
      next: "Next",
      staffLog: "Staff Log",
      carHandover: "Car Handover",
      staffManagement: "Staff Management",

      // Admin - Top Car Rental
      topCarRental: "Top 5 Car Rental",
      sportCar: "Sport Car",
      suv: "SUV",
      coupe: "Coupe",
      hatchback: "Hatchback",
      mpv: "MPV",

      // Admin - Recent Transaction
      recentTransaction: "Recent Transaction",

      // Admin - Operations Dashboard
      operationsDashboardTitle: "Operations Dashboard",
      operationsDashboardSubtitle: "High-level overview to manage user roles and system settings",
      lastHour: "Last Hour",
      last24Hours: "Last 24 Hours",
      last7Days: "Last 7 Days",
      last30Days: "Last 30 Days",
      refreshData: "Refresh Data",
      systemUptime: "System Uptime",
      activeUsers: "Active Users",
      totalRequests: "Total Requests",
      errorRate: "Error Rate",
      responseTime: "Response Time",
      serverLoad: "Server Load",
      serviceStatus: "Service Status",
      serviceStatusSubtitle: "Monitor all system services and their health",
      operational: "Operational",
      degraded: "Degraded",
      maintenance: "Maintenance",
      outage: "Outage",
      uptime: "Uptime",
      avgResponse: "avg response",
      recentAlerts: "Recent Alerts",
      recentAlertsSubtitle: "System notifications and operational updates",
      high: "high",
      medium: "medium",
      low: "low",
      viewAllAlerts: "View All Alerts",
      userRoleManagement: "User Role Management",
      userRoleManagementSubtitle: "Manage user permissions and system access",
      adminUsers: "Admin Users",
      manageAdmins: "Manage Admins",
      regularUsers: "Regular Users",
      viewUsers: "View Users",
      permissions: "Permissions",
      configure: "Configure",
      roleManagement: "Account Number",
      RoleManagementUsers: "User",
      RoleManagementCarOwners: "Car Owners",
      RoleManagementStaff: "Staff",
      activeCars: "Active Cars",
      carsInUse: "Car in use",
      TotalBookings: "Total Bookings",

      // Admin - Staff Management
      StaffManagement: "Staff Management",
      viewAndManageStaffAndCarOwners: "View and manage staff and car owners",
      exportData: "Export Data",
      loading: "Loading...",
      searchStaff: "Search staff by name, email, or phone",
      allRoles: "All Roles",
      staff: "Staff",
      carOwner: "Car Owner",
      showing: "Showing",
      of: "of",
      members: "members",
      noStaffFound: "No Staff Found",
      noStaffMatchingFilters: "No staff members match your current filters",
      member: "Member",
      phone: "Phone",
      email: "Email",
      role: "Role",
      joinDate: "Join Date",
      actions: "Actions",
      view: "View",
      suspend: "Suspend",

      // Staff Status
      active: "Active",
      pending: "Pending",
      suspended: "Suspended",

      // Staff Roles
      Staff: "Staff",
      User: "User",

      // Error Messages
      failedToLoadStaffData: "Failed to load staff data",

      // Admin - Staff Logs
      StaffLogs: "Staff Activity Logs",
      viewStaffActivityLogs: "View and monitor staff activity logs",
      searchStaffLogs: "Search staff logs...",
      allActions: "All Actions",
      checkIn: "Check-in",
      checkOut: "Check-out",
      logs: "logs",
      action: "Action",
      timestamp: "Timestamp",
      handoverId: "Handover ID",
      userAgent: "User Agent",
      logDetails: "Log Details",
      logId: "Log ID",
      ipAddress: "IP Address",

      // Admin - Car Handover Logs
      CarHandoverLogs: "Car Handover Logs",
      viewCarHandoverLogs: "View and monitor car handover activity logs",
      searchCarHandoverLogs: "Search car handover logs...",
      type: "Type",
      pickup: "Pickup",
      return: "Return",
      description: "Description",
      scheduleId: "Schedule ID",
      verificationMethod: "Verification Method",
    }
  },
  vi: {
    translation: {
      // Admin - Sidebar
      mainMenu: "MENU CHÍNH",
      dashboard: "Bảng điều khiển",
      operationsDashboard: "Bảng điều khiển vận hành",
      transactionMonitoring: "Giám sát giao dịch",
      carRent: "Thuê xe",
      insight: "Thông tin chi tiết",
      reimburse: "Hoàn tiền",
      inbox: "Hộp thư",
      calendar: "Lịch",
      preferences: "TÙY CHỌN",
      settings: "Cài đặt",
      helpCenter: "Trung tâm trợ giúp",
      darkMode: "Chế độ tối",
      ownerPage: "Trang Quản Lý",
      staffPage: "Trang Nhân Viên",
      // Admin - Status Overview
      statusOverview: "Tổng quan trạng thái booking và xe",
      status: "Trạng thái",
      paid: "Đã thanh toán",
      unpaid: "Chưa thanh toán",
      rented: "Đang thuê",
      overdue: "Quá hạn",
      available: "Có sẵn",
      returned: "Đã trả",
      previous: "Trước",
      next: "Tiếp",
      staffLog: "Nhật ký theo dõi",
      carHandover: "Nhật ký bàn giao xe",
      staffManagement: "Quản lý nhân viên",
      createStaff: "Tạo tài khoản Nhân viên",
      
      // Admin - Create Staff
      createStaffTitle: "Tạo tài khoản nhân viên",
      createStaffUsername: "Tên đăng nhập",
      createStaffUsernamePlaceholder: "Nhập tên đăng nhập",
      createStaffUsernameRequired: "Tên đăng nhập là bắt buộc",
      createStaffPassword: "Mật khẩu",
      createStaffPasswordPlaceholder: "Nhập mật khẩu",
      createStaffPasswordRequired: "Mật khẩu là bắt buộc",
      createStaffPasswordMinLength: "Mật khẩu phải có ít nhất 6 ký tự",
      createStaffFullname: "Họ và tên",
      createStaffFullnamePlaceholder: "Nhập họ và tên",
      createStaffFullnameRequired: "Họ và tên là bắt buộc",
      createStaffEmail: "Email",
      createStaffEmailPlaceholder: "Nhập địa chỉ email",
      createStaffEmailRequired: "Email là bắt buộc",
      createStaffEmailInvalid: "Vui lòng nhập địa chỉ email hợp lệ",
      createStaffPhoneNumber: "Số điện thoại",
      createStaffPhoneNumberPlaceholder: "Nhập số điện thoại",
      createStaffPhoneRequired: "Số điện thoại là bắt buộc",
      createStaffPhoneInvalid: "Số điện thoại phải có 10 chữ số bắt đầu bằng 0 (ví dụ: 0969468855)",
      createStaffDateOfBirth: "Ngày sinh",
      createStaffDateOfBirthRequired: "Ngày sinh là bắt buộc",
      createStaffAddress: "Địa chỉ",
      createStaffAddressPlaceholder: "Nhập địa chỉ",
      createStaffAddressRequired: "Địa chỉ là bắt buộc",
      createStaffGender: "Giới tính",
      createStaffGenderMale: "Nam",
      createStaffGenderFemale: "Nữ",
      createStaffCreateButton: "Tạo tài khoản nhân viên",
      createStaffCreating: "Đang tạo...",
      createStaffSuccessMessage: "Tạo tài khoản nhân viên thành công!",
      createStaffErrorMessage: "Không thể tạo tài khoản nhân viên. Vui lòng thử lại.",
      
      // Admin - Top Car Rental
      topCarRental: "Top 5 Xe Cho Thuê",
      sportCar: "Xe thể thao",
      suv: "SUV",
      coupe: "Coupe",
      hatchback: "Hatchback",
      mpv: "MPV",

      // Admin - Recent Transaction
      recentTransaction: "Giao dịch gần đây",

      // Admin - Operations Dashboard
      operationsDashboardTitle: "Bảng điều khiển vận hành",
      operationsDashboardSubtitle: "Tổng quan cấp cao để quản lý vai trò người dùng và cài đặt hệ thống",
      lastHour: "Giờ qua",
      last24Hours: "24 giờ qua",
      last7Days: "7 ngày qua",
      last30Days: "30 ngày qua",
      refreshData: "Làm mới dữ liệu",
      systemUptime: "Thời gian hoạt động",
      activeUsers: "Người dùng hoạt động",
      totalRequests: "Tổng yêu cầu",
      errorRate: "Tỷ lệ lỗi",
      responseTime: "Thời gian phản hồi",
      serverLoad: "Tải máy chủ",
      serviceStatus: "Trạng thái dịch vụ",
      serviceStatusSubtitle: "Giám sát tất cả dịch vụ hệ thống và tình trạng",
      operational: "Hoạt động",
      degraded: "Suy giảm",
      maintenance: "Bảo trì",
      outage: "Ngừng hoạt động",
      uptime: "Thời gian hoạt động",
      avgResponse: "phản hồi TB",
      recentAlerts: "Cảnh báo gần đây",
      recentAlertsSubtitle: "Thông báo hệ thống và cập nhật vận hành",
      high: "cao",
      medium: "trung bình",
      low: "thấp",
      viewAllAlerts: "Xem tất cả cảnh báo",
      userRoleManagement: "Quản lý vai trò người dùng",
      userRoleManagementSubtitle: "Quản lý quyền người dùng và truy cập hệ thống",
      adminUsers: "Người dùng quản trị",
      manageAdmins: "Quản lý quản trị viên",
      regularUsers: "Người dùng thường",
      viewUsers: "Xem người dùng",
      permissions: "Quyền hạn",
      configure: "Cấu hình",
      roleManagement: "Số lượng tài khoản",
      RoleManagementUsers: "Người dùng",
      RoleManagementCarOwners: "Quản lý",
      RoleManagementStaff: "Nhân viên",
      activeCars: "Xe đang hoạt động",
      carsInUse: "Xe đang vận hành",
      TotalBookings: "Tổng số đơn đặt",

      // Admin - Staff Management
      StaffManagement: "Quản lý nhân viên",
      viewAndManageStaffAndCarOwners: "Xem và quản lý nhân viên và chủ xe",
      exportData: "Xuất dữ liệu",
      loading: "Đang tải...",
      searchStaff: "Tìm kiếm nhân viên theo tên, email hoặc số điện thoại",
      allRoles: "Tất cả vai trò",
      staff: "Nhân viên",
      carOwner: "Chủ xe",
      showing: "Hiển thị",
      of: "trong tổng số",
      members: "thành viên",
      noStaffFound: "Không tìm thấy nhân viên",
      noStaffMatchingFilters: "Không có nhân viên nào phù hợp với bộ lọc hiện tại",
      member: "Thành viên",
      phone: "Số điện thoại",
      email: "Email",
      role: "Vai trò",
      joinDate: "Ngày tham gia",
      actions: "Hành động",
      view: "Xem",
      suspend: "Tạm ngưng",

      // Staff Status
      active: "Hoạt động",
      pending: "Chờ xử lý",
      suspended: "Tạm ngưng",

      // Staff Roles
      Staff: "Nhân viên",
      User: "Người dùng",

      // Error Messages
      failedToLoadStaffData: "Không thể tải dữ liệu nhân viên",

      // Admin - Staff Logs
      StaffLogs: "Nhật ký hoạt động nhân viên",
      viewStaffActivityLogs: "Xem và giám sát nhật ký hoạt động nhân viên",
      searchStaffLogs: "Tìm kiếm nhật ký nhân viên...",
      allActions: "Tất cả hành động",
      checkIn: "Đăng nhập",
      checkOut: "Đăng xuất",
      logs: "nhật ký",
      action: "Hành động",
      timestamp: "Thời gian",
      handoverId: "ID bàn giao",
      userAgent: "Trình duyệt",
      logDetails: "Chi tiết nhật ký",
      logId: "ID nhật ký",
      ipAddress: "Địa chỉ IP",

      // Admin - Car Handover Logs
      CarHandoverLogs: "Nhật ký bàn giao xe",
      viewCarHandoverLogs: "Xem và giám sát nhật ký hoạt động bàn giao xe",
      searchCarHandoverLogs: "Tìm kiếm nhật ký bàn giao xe...",
      type: "Loại",
      pickup: "Nhận xe",
      return: "Trả xe",
      description: "Mô tả",
      scheduleId: "ID lịch trình",
      verificationMethod: "Phương thức xác minh",
      statusBookingAdmin: "Trạng thái booking",
      statusCarAdmin: "Trạng thái xe",
    }
  }
};