export const staffTranslate = {
  en: {
    translation: {
      // Car Registration Status
      carRegistrationStatus: "Car Registration Status",
      totalCars: "Total Cars",
      approvedCars: "Approved Cars",
      pendingCars: "Pending Cars",
      rejectedCars: "Rejected Cars",
      carStatusDistribution: "Car Status Distribution",
      approvalRate: "Approval Rate",
      carsApproved: "cars approved",
      noDataAvailable: "No data available",

      // Customer Account Overview
      customerAccountOverview: "Customer Account Overview",
      totalUsers: "Total Users",
      verifiedUsers: "Verified Users",
      unverifiedUsers: "Unverified Users",
      userVerificationStatus: "User Verification Status",
      userStatistics: "User Statistics",
      verificationRate: "Verification Rate",
      usersVerified: "users verified",
      // Booking Modal
      bookingDetails: "Booking Details",
      cancelBooking: "Cancel Booking",
      resolveOverdueBooking: "Resolve Overdue Booking",
      bookingId: "Booking ID",
      bookingNumber: "Booking Number",
      customer: "Customer",
      carOwner: "Car Owner",
      totalAmount: "Total Amount",
      startDate: "Start Date",
      endDate: "End Date",
      paymentStatus: "Payment Status",
      createdAt: "Created At",
      notes: "Notes",
      edit: "Edit",
      resolve: "Resolve",
      saveChanges: "Save Changes",
      pending: "Pending",
      active: "Active",
      completed: "Completed",
      confirmed: "Confirmed",
      cancelled: "Cancelled",
      addNotesPlaceholder: "Add any notes about this booking...",
      cancelBookingWarning: "Are you sure you want to cancel booking",
      thisActionCannotBeUndone: "This action cannot be undone.",
      bookingDetailsLabel: "Booking Details:",
      duration: "Duration",
      amount: "Amount",
      cancellationReason: "Cancellation Reason",
      provideCancellationReason: "Please provide a reason for cancellation...",
      keepBooking: "Keep Booking",
      resolveOverdueWarning: "Mark booking",
      asCompleted: "as completed.",
      resolveOverdueDescription: "This will resolve the overdue status.",
      expectedEnd: "Expected End",
      currentNotes: "Current Notes",
      noNotes: "No notes",
      markAsCompleted: "Mark as Completed",
      pickupDetails: "Pickup Details",
      dropoffDetails: "Dropoff Details",

      // Car Owner Modal
      carOwnerDetails: "Car Owner Details",
      editCarOwner: "Edit Car Owner",
      suspendCarOwner: "Suspend Car Owner",
      name: "Name",
      phone: "Phone",
      registrationDate: "Registration Date",
      verificationStatus: "Verification Status",
      suspend: "Suspend",
      suspendCarOwnerAccount: "Suspend Car Owner Account",
      suspendAccountWarning: "Are you sure you want to suspend",
      suspendAccountDescription: "'s account? This will prevent them from accessing their account and listing new cars.",
      accountDetails: "Account Details:",
      suspendAccount: "Suspend Account",
      suspended: "Closed",
      noDataToExport: "No Data To Export",
      exportSuccessful: "Export Successful",
      exportFailed: "Export Failed",

      // Customer Modal
      customerDetails: "Car Customer Details",
      editCustomer: "Edit Car Customer",
      suspendCustomer: "Suspend Car Customer",
      suspendCustomerAccount: "Suspend Customer Account",
      suspendCustomerWarning: "Are you sure you want to suspend",
      suspendCustomerDescription: "'s account? This will prevent them from accessing their account and bookings new cars.",
      totalBookings: "Total Bookings",
      confirmedBookings: "Confirmed Bookings",
      completedBookings: "Completed Bookings",
      canceledBookings: "Canceled Bookings",
      totalRevenue: "Total Revenue",
      totalSpent: "Total Spent",
      lastBooking: "Last Booking",
      noBookingsYet: "No bookings yet",
      complianceIssues: "Compliance Issues",
      issues: "issues",
      noIssues: "No issues",
      verified: "Verified",
      rejected: "Rejected",
      customerSuspendedSuccessfully: "Customer suspended successfully!",
      failedToSuspendCustomer: "Failed to suspend customer",
      // Staff Components
      bookingMonitoring: "Booking Monitoring",
      monitorAndManageBookings: "Monitor and manage all booking activities",
      exportReport: "Export Report",
      createManualBooking: "Create Manual Booking",
      allDates: "All Dates",
      thisWeek: "This Week",
      thisMonth: "This Month",
      showing: "Showing",
      of: "of",
      bookings: "bookings",
      to: "to",
      actions: "Actions",
      view: "View",
      activate: "Activate",
      message: "Message",

      carOwnerManagement: "Car Owner Management",
      viewAndManageCarOwners: "View and manage car owner accounts",
      exportData: "Export Data",
      searchCarOwners: "Search car owners...",
      carOwners: "car owners",
      verification: "Verification",
      owner: "Owner",
      allStatus: "All Status",
      carsListed: "Cars Listed",
      totalEarnings: "Total Earnings",
      lastActive: "Last Active",
      previous: "Previous",
      next: "Next",
      loading: "Loading",

      customerManagement: "Customer Management",
      viewAndManageCustomers: "View and manage customer accounts",
      sendBulkMessage: "Send Bulk Message",
      searchCustomers: "Search customers...",
      totalCustomers: "Total Customers",
      activeCustomers: "Active Customers",
      pendingVerification: "Pending Verification",
      customers: "customers",
      tier: "Tier",
      none: "None",

      platformOverview: "System Overview",

      notificationCenter: "Notification Center",
      sendSystemWideNotifications: "Send system-wide notifications to users",
      createNotification: "Create Notification",
      notificationHistory: "Notification History",
      notificationTitle: "Notification Title",
      enterNotificationTitle: "Enter notification title...",
      messageContent: "Message Content",
      enterYourMessage: "Enter your message...",
      targetAudience: "Target Audience",
      allUsers: "All Users",
      customersOnly: "Customers Only",
      carOwnersOnly: "Car Owners Only",
      priorityLevel: "Priority Level",
      lowPriority: "Low Priority",
      normalPriority: "Normal Priority",
      highPriority: "High Priority",
      deliveryMethod: "Delivery Method",
      inAppNotification: "In-App Notification",
      bothInAppEmail: "Both In-App & Email",
      schedule: "Schedule",
      sendImmediately: "Send Immediately",
      scheduleForLater: "Schedule for Later",
      thisNotificationWillBeSent: "This notification will be sent to",
      users: "users",
      saveDraft: "Save Draft",
      sendNotification: "Send Notification",
      sent: "Sent",
      audience: "Audience",
      recipients: "Recipients",
      read: "Read",
      viewDetails: "View Details",
      duplicate: "Duplicate",

      pendingVerifications: "Pending Verifications",
      review: "Review",
      viewAllPendingVerifications: "View All Pending Verifications",

      recentActivities: "Recent Activities",
      newBookingCreated: "New booking created",
      carOwnerVerificationCompleted: "Car owner verification completed",
      bookingCancelled: "Booking cancelled",
      customerAccountUpdated: "Customer account updated",
      bookingCompleted: "Booking completed",
      by: "by",
      confirmed: "Confirmed",
      approved: "Approved",
      updated: "Updated",
      failed: "Failed",
      expired: "Expired",
      justNow: "Just now",
      minutesAgo: "minutes ago",
      hoursAgo: "hours ago",
      daysAgo: "days ago",
      noRecentActivities: "No recent activities",

      staffMenu: "STAFF MENU",
      carOwnerAccounts: "Car Owner Accounts",
      monitorBookings: "Monitor Bookings",
      customerAccounts: "Customer Accounts",
      sendNotifications: "Send Notifications",
      createParkingLot: "Create Parking Lot",
      registrationDocuments: "Registration Documents",
      driverLicenseApprove: "Driver License Approve",
      reviewAndApproveDriverLicenses: "Review And Approve Driver Licenses",
      noLicensesFound: "No Licenses Found",
      searchLicenses: "Search licenses...",
      licenses: "licenses",
      autoApproved: "Auto Approved",
      manualApproved: "Manual Approved",
      needManualCheck: "Need Manual Check",
      rentalMonitoring: "Rental Monitoring",
      // Parking Lot Creation
      parkingLotName: "Parking Lot Name",
      enterParkingLotName: "Enter parking lot name",
      parkingLotNameRequired: "Parking lot name is required",
      addressRequired: "Address is required",
      cityRequired: "City is required",
      validCapacityRequired: "Valid capacity is required",
      contactNumberRequired: "Contact number is required",
      enterAddress: "Enter address",
      useCurrent: "Use Current",
      getting: "Getting...",
      coordinates: "Coordinates",
      city: "City",
      enterCity: "Enter city",
      capacity: "Capacity",
      enterParkingCapacity: "Enter parking capacity",
      contactNumber: "Contact Number",
      enterContactNumber: "Enter contact number",
      enterAdditionalNotes: "Enter any additional notes...",
      createParkingLotButton: "Create Parking Lot",
      creating: "Creating...",
      parkingLotCreatedSuccessfully: "Parking lot created successfully!",
      failedToCreateParkingLot: "Failed to create parking lot",
      addNewParkingLot: "Add a new parking lot to the system",
      failedToGetCurrentLocation: "Failed to get current location",

      noBookingsFound: "No Booking Found",
      allStatus: "All Status",
      allPaymentStatus: "All Payment Status",
      searchBookings: "Search Bookings",
      // Calendar Components
      month: "Month",
      week: "Week",
      day: "Day",
      agenda: "Agenda",
      noEventsScheduled: "No events scheduled",
      event: "event",
      newEvent: "New Event",
      exportToOutlook: "Export to Outlook",
      mon: "Mon",
      tue: "Tue",
      wed: "Wed",
      thu: "Thu",
      fri: "Fri",
      sat: "Sat",
      sun: "Sun",
      monday: "Monday",
      tuesday: "Tuesday",
      wednesday: "Wednesday",
      thursday: "Thursday",
      friday: "Friday",
      saturday: "Saturday",
      sunday: "Sunday",
      january: "January",
      february: "February",
      march: "March",
      april: "April",
      may: "May",
      june: "June",
      july: "July",
      august: "August",
      september: "September",
      october: "October",
      november: "November",
      december: "December",
      loadingCalendar: "Loading calendar...",
      newBooking: "New Booking",
      deleteBooking: "Delete Booking",
      areYouSureDeleteBooking: "Are you sure you want to delete this booking?",
      saving: "Saving...",
      create: "Create",
      update: "Update",
      close: "Close",
      more: "more",
      allEvents: "All Events",

      //Create Parlot
      selectCarOwner: "Select Car Owner",
      noCarOwnersFound: "No Car Owners Found",

      //Report Car
      reportcar: "Report Car",
      reportCarMonitoring: "Report Car Monitoring",
      monitorAndManageReport: "Monitor and manage all report request",
      noReportFound: "No Report Found",
      reportNo: "Report",
      reportUser: "Report User",
      noBookings: "No Bookings",
      bookingStats: "Booking Stats",

      //Report User
      reportingUser: "Reporting User",
      deductedPoints: "Deducted Points",
      pointsToDeductFromUser: "Points To Deduct From User",
      enterReportTitle: "Enter Report Title",
      enterReportContent: "Enter Report Content",
      submitReport: "Submit Report",
      sortByBehaviourScore: "Sort By Behaviour Score",
      lowestToHighest: "Lowest To Highest",
      highestToLowest: "Highest To Lowest",

      //regdoc
      carRegistrationDocuments: "Car Registration Documents",
      reviewAndApproveCarRegistrationDocuments: "Review and approve car registration documents",
      searchDocuments: "Search documents...",
      documents: "documents",
      userFullName: "User Full Name",
      carInfo: "Car Information",
      documentImage: "Document Image",
      submittedDate: "Submitted Date",
      status: "Status",
      registrationDocumentDetails: "Registration Document Details",
      documentImages: "Document Images",
      noDocumentImagesAvailable: "No document images available",
      approveRegistrationDocument: "Approve Registration Document",
      areYouSureApprove: "Are you sure you want to approve this registration document?",
      user: "User",
      car: "Car",
      carId: "Car ID",
      confirm: "Confirm",
      cancel: "Cancel",
      approving: "Approving...",
      approve: "Approve",
      rejecting: "Rejecting...",
      reject: "Reject",
      errorLoadingDocuments: "Error loading documents",
      retry: "Retry",
      noDocumentsFound: "No documents found",
      areYouSureReject: "Are you sure you want to reject this registration document?",
      rejectRegistrationDocument: "Reject Registration Document",
      failedToApproveRegistrationDocument: "Failed to approve registration document",
      registrationDocumentApprovedSuccessfully: "Registration document approved successfully",
      failedToRejectRegistrationDocument: "Failed to reject registration document",
      registrationDocumentRejectedSuccessfully: "Registration document rejected successfully",
      denied: "Denied",
      //needmanualcheck
      statusNeedManualCheck: "Need Manual Check",
      behaviourScore: "Behaviour Score",
      tryAdjustingFilters: "Try Adjusting Filters",
      noCustomersFound: "No Customers Found",
    }
  },
  vi: {
    translation: {
      // Car Registration Status
      carRegistrationStatus: "Trạng thái đăng ký xe",
      totalCars: "Tổng số xe",
      approvedCars: "Xe đã phê duyệt",
      pendingCars: "Xe chờ phê duyệt",
      rejectedCars: "Xe bị từ chối",
      carStatusDistribution: "Phân bố trạng thái xe",
      approvalRate: "Tỷ lệ phê duyệt",
      carsApproved: "xe đã được phê duyệt",
      noDataAvailable: "Không có dữ liệu",

      // Customer Account Overview
      customerAccountOverview: "Tổng quan tài khoản khách hàng",
      totalUsers: "Tổng số người dùng",
      verifiedUsers: "Người dùng đã xác minh",
      unverifiedUsers: "Người dùng chưa xác minh",
      userVerificationStatus: "Trạng thái xác minh người dùng",
      userStatistics: "Thống kê người dùng",
      verificationRate: "Tỷ lệ xác minh",
      usersVerified: "người dùng đã xác minh",
      // Booking Modal
      bookingDetails: "Chi tiết đặt xe",
      cancelBooking: "Hủy đặt xe",
      resolveOverdueBooking: "Giải quyết đặt xe quá hạn",
      bookingId: "Mã đặt xe",
      bookingNumber: "Mã đặt xe",
      customer: "Khách hàng",
      carOwner: "Chủ xe",
      totalAmount: "Tổng tiền",
      startDate: "Ngày bắt đầu",
      endDate: "Ngày kết thúc",
      paymentStatus: "Trạng thái thanh toán",
      createdAt: "Ngày tạo",
      notes: "Ghi chú",
      edit: "Chỉnh sửa",
      resolve: "Giải quyết",
      saveChanges: "Lưu thay đổi",
      pending: "Chờ xử lý",
      active: "Đang hoạt động",
      completed: "Hoàn thành",
      confirmed: "Đã xác nhận",
      cancelled: "Đã hủy",
      addNotesPlaceholder: "Thêm ghi chú về đặt xe này...",
      cancelBookingWarning: "Bạn có chắc chắn muốn hủy đặt xe",
      thisActionCannotBeUndone: "Hành động này không thể hoàn tác.",
      bookingDetailsLabel: "Chi tiết đặt xe:",
      duration: "Thời gian",
      amount: "Số tiền",
      cancellationReason: "Lý do hủy",
      provideCancellationReason: "Vui lòng cung cấp lý do hủy...",
      keepBooking: "Giữ đặt xe",
      resolveOverdueWarning: "Đánh dấu đặt xe",
      asCompleted: "là hoàn thành.",
      resolveOverdueDescription: "Điều này sẽ giải quyết trạng thái quá hạn.",
      expectedEnd: "Ngày kết thúc dự kiến",
      currentNotes: "Ghi chú hiện tại",
      noNotes: "Không có ghi chú",
      markAsCompleted: "Đánh dấu hoàn thành",
      pickupDetails: "Địa điểm nhận xe",
      dropoffDetails: "Địa điểm trả xe",

      // Car Owner Modal
      carOwnerDetails: "Chi tiết chủ xe",
      editCarOwner: "Chỉnh sửa chủ xe",
      suspendCarOwner: "Tạm ngưng chủ xe",
      name: "Tên",
      phone: "Số điện thoại",
      registrationDate: "Ngày đăng ký",
      verificationStatus: "Trạng thái xác minh",
      suspend: "Tạm ngưng",
      suspendCarOwnerAccount: "Tạm ngưng tài khoản chủ xe",
      suspendAccountWarning: "Bạn có chắc chắn muốn tạm ngưng tài khoản của",
      suspendAccountDescription: "? Điều này sẽ ngăn họ truy cập tài khoản và đăng xe mới.",
      accountDetails: "Chi tiết tài khoản:",
      suspendAccount: "Tạm ngưng tài khoản",
      suspended: "Đã tạm ngưng",

      // Customer Modal
      customerDetails: "Chi tiết khách hàng",
      editCustomer: "Chỉnh sửa khách hàng",
      suspendCustomer: "Tạm ngưng khách hàng",
      suspendCustomerAccount: "Tạm ngưng tài khoản khách hàng",
      suspendCustomerWarning: "Bạn có chắc chắn muốn tạm ngưng tài khoản của",
      suspendCustomerDescription: "? Điều này sẽ ngăn họ truy cập tài khoản và đặt xe mới.",
      totalBookings: "Tổng số đặt xe",
      confirmedBookings: "Đặt xe đã xác nhận",
      completedBookings: "Đặt xe đã hoàn thành",
      canceledBookings: "Đơn đặt xe đã hủy",
      totalRevenue: "Tổng doanh thu",
      totalSpent: "Tổng chi tiêu",
      lastBooking: "Đặt xe lần cuối",
      noBookingsYet: "Chưa có đặt xe",
      complianceIssues: "Vấn đề tuân thủ",
      issues: "vấn đề",
      noIssues: "Không có vấn đề",
      verified: "Đã xác minh",
      rejected: "Đã từ chối",

      // Staff Components
      bookingMonitoring: "Giám sát đặt xe",
      monitorAndManageBookings: "Giám sát và quản lý tất cả hoạt động đặt xe",
      exportReport: "Xuất báo cáo",
      createManualBooking: "Tạo đặt xe thủ công",
      allDates: "Tất cả ngày",
      thisWeek: "Tuần này",
      thisMonth: "Tháng này",
      showing: "Hiển thị",
      of: "của",
      bookings: "đặt xe",
      to: "đến",
      actions: "Hành động",
      view: "Xem",
      activate: "Kích hoạt",
      message: "Tin nhắn",

      carOwnerManagement: "Quản lý chủ xe",
      viewAndManageCarOwners: "Xem và quản lý tài khoản chủ xe",
      exportData: "Xuất dữ liệu",
      searchCarOwners: "Tìm kiếm chủ xe...",
      carOwners: "chủ xe",
      verification: "Xác minh",
      owner: "Chủ xe",
      allStatus: "Tất cả trạng thái",
      carsListed: "Xe đã đăng",
      totalEarnings: "Tổng thu nhập",
      lastActive: "Hoạt động lần cuối",
      previous: "Trước",
      next: "Tiếp",
      loading: "Đang tải",

      customerManagement: "Quản lý khách hàng",
      viewAndManageCustomers: "Xem và quản lý tài khoản khách hàng",
      sendBulkMessage: "Gửi tin nhắn hàng loạt",
      searchCustomers: "Tìm kiếm khách hàng...",
      totalCustomers: "Tổng số khách hàng",
      activeCustomers: "Khách hàng hoạt động",
      pendingVerification: "Chờ xác minh",
      customers: "khách hàng",
      tier: "Hạng",
      none: "Không có",

      platformOverview: "Tổng quan nền tảng",

      notificationCenter: "Trung tâm thông báo",
      sendSystemWideNotifications: "Gửi thông báo toàn hệ thống cho người dùng",
      createNotification: "Tạo thông báo",
      notificationHistory: "Lịch sử thông báo",
      notificationTitle: "Tiêu đề thông báo",
      enterNotificationTitle: "Nhập tiêu đề thông báo...",
      messageContent: "Nội dung tin nhắn",
      enterYourMessage: "Nhập tin nhắn của bạn...",
      targetAudience: "Đối tượng mục tiêu",
      allUsers: "Tất cả người dùng",
      customersOnly: "Chỉ khách hàng",
      carOwnersOnly: "Chỉ chủ xe",
      priorityLevel: "Mức độ ưu tiên",
      lowPriority: "Ưu tiên thấp",
      normalPriority: "Ưu tiên bình thường",
      highPriority: "Ưu tiên cao",
      deliveryMethod: "Phương thức gửi",
      inAppNotification: "Thông báo trong ứng dụng",
      bothInAppEmail: "Cả trong ứng dụng & Email",
      schedule: "Lịch trình",
      sendImmediately: "Gửi ngay",
      scheduleForLater: "Lên lịch sau",
      thisNotificationWillBeSent: "Thông báo này sẽ được gửi đến",
      users: "người dùng",
      saveDraft: "Lưu nháp",
      sendNotification: "Gửi thông báo",
      sent: "Đã gửi",
      audience: "Đối tượng",
      recipients: "Người nhận",
      read: "Đã đọc",
      viewDetails: "Xem chi tiết",
      duplicate: "Nhân bản",

      pendingVerifications: "Xác minh đang chờ",
      review: "Xem xét",
      viewAllPendingVerifications: "Xem tất cả xác minh đang chờ",

      recentActivities: "Hoạt động gần đây",
      newBookingCreated: "Đặt xe mới được tạo",
      carOwnerVerificationCompleted: "Xác minh chủ xe hoàn tất",
      bookingCancelled: "Đặt xe đã hủy",
      customerAccountUpdated: "Tài khoản khách hàng đã cập nhật",
      bookingCompleted: "Đặt xe hoàn thành",
      by: "bởi",
      confirmed: "đã xác nhận",
      approved: "đã phê duyệt",
      updated: "đã cập nhật",
      failed: "Thất bại",
      expired: "Hết hạn",
      justNow: "Vừa xong",
      minutesAgo: "phút trước",
      hoursAgo: "giờ trước",
      daysAgo: "ngày trước",
      noRecentActivities: "Không có hoạt động gần đây",

      staffMenu: "MENU NHÂN VIÊN",
      carOwnerAccounts: "Tài khoản chủ xe",
      monitorBookings: "Giám sát đặt xe",
      rentalMonitoring: "Giám sát thuê xe",
      customerAccounts: "Tài khoản khách hàng",
      sendNotifications: "Gửi thông báo",
      createParkingLot: "Tạo Bãi Đỗ Xe",
      registrationDocuments: "Tài liệu đăng ký",
      driverLicenseApprove: "Phê duyệt bằng lái xe",
      reviewAndApproveDriverLicenses: "Xem xét và phê duyệt bằng lái xe",
      noLicensesFound: "Không tìm thấy bằng lái xe",
      searchLicenses: "Tìm kiếm bằng lái xe...",
      licenses: "bằng lái xe",
      autoApproved: "Tự động phê duyệt",
      manualApproved: "Phê duyệt thủ công",
      needManualCheck: "Cần kiểm tra thủ công",

      // Parking Lot Creation
      parkingLotName: "Tên Bãi Đỗ Xe",
      enterParkingLotName: "Nhập tên bãi đỗ xe",
      parkingLotNameRequired: "Tên bãi đỗ xe là bắt buộc",
      addressRequired: "Địa chỉ là bắt buộc",
      cityRequired: "Thành phố là bắt buộc",
      validCapacityRequired: "Sức chứa hợp lệ là bắt buộc",
      contactNumberRequired: "Số liên hệ là bắt buộc",
      enterAddress: "Nhập địa chỉ",
      useCurrent: "Dùng Vị Trí Hiện Tại",
      getting: "Đang lấy...",
      coordinates: "Tọa độ",
      city: "Thành phố",
      enterCity: "Nhập thành phố",
      capacity: "Sức chứa",
      enterParkingCapacity: "Nhập sức chứa bãi đỗ",
      contactNumber: "Số Liên Hệ",
      enterContactNumber: "Nhập số liên hệ",
      enterAdditionalNotes: "Nhập ghi chú bổ sung...",
      createParkingLotButton: "Tạo Bãi Đỗ Xe",
      creating: "Đang tạo...",
      parkingLotCreatedSuccessfully: "Tạo bãi đỗ xe thành công!",
      failedToCreateParkingLot: "Không thể tạo bãi đỗ xe",
      addNewParkingLot: "Thêm bãi đỗ xe mới vào hệ thống",
      failedToGetCurrentLocation: "Không thể lấy vị trí hiện tại",

      noBookingsFound: "Không có đơn đặt xe",
      allStatus: "Tất cả trạng thái",
      allPaymentStatus: "Tất cả trạng thái thanh toán",
      searchBookings: "Tìm đơn đặt hàng",
      // Calendar Components
      month: "Tháng",
      week: "Tuần",
      day: "Ngày",
      agenda: "Lịch trình",
      noEventsScheduled: "Không có sự kiện nào",
      event: "sự kiện",
      newEvent: "Sự kiện mới",
      exportToOutlook: "Xuất sang Outlook",
      mon: "T2",
      tue: "T3",
      wed: "T4",
      thu: "T5",
      fri: "T6",
      sat: "T7",
      sun: "CN",
      monday: "Thứ hai",
      tuesday: "Thứ ba",
      wednesday: "Thứ tư",
      thursday: "Thứ năm",
      friday: "Thứ sáu",
      saturday: "Thứ bảy",
      sunday: "Chủ nhật",
      january: "Tháng một",
      february: "Tháng hai",
      march: "Tháng ba",
      april: "Tháng tư",
      may: "Tháng năm",
      june: "Tháng sáu",
      july: "Tháng bảy",
      august: "Tháng tám",
      september: "Tháng chín",
      october: "Tháng mười",
      november: "Tháng mười một",
      december: "Tháng mười hai",
      loadingCalendar: "Đang tải lịch...",
      newBooking: "Đặt xe mới",
      deleteBooking: "Xóa đặt xe",
      areYouSureDeleteBooking: "Bạn có chắc chắn muốn xóa đặt xe này?",
      saving: "Đang lưu...",
      create: "Tạo",
      update: "Cập nhật",
      close: "Đóng",
      more: "thêm",
      allEvents: "Tất Cả Sự Kiện",
      //Create Parlot
      selectCarOwner: "Chọn quản lý bãi xe",
      noCarOwnersFound: "Không tìm thấy",
      //Report Car
      reportcar: "Khiếu Nại Xe",
      reportCarMonitoring: "Quản lý khiếu nại xe",
      monitorAndManageReport: "Quản lý và giám sát khiếu nại về xe",
      noReportFound: "Không thấy khiếu nại",
      reportNo: "Khiếu nại số",
      reportUser: "Khiếu Nại người dùng",
      noBookings: "Không có đơn đặt",
      bookingStats: "Thống kê đặt chỗ",

      //Report User
      reportingUser: "Người dùng bị báo cáo",
      deductedPoints: "Điểm bị trừ",
      pointsToDeductFromUser: "Điểm cần trừ từ người dùng",
      enterReportTitle: "Nhập tiêu đề báo cáo",
      enterReportContent: "Nhập nội dung báo cáo",
      submitReport: "Gửi báo cáo",
      sortByBehaviourScore: "Sắp xếp theo điểm hành vi",
      lowestToHighest: "Từ cao nhất đến thấp nhất",
      highestToLowest: "Từ thấp nhất đến cao nhất",
      //regdoc
      carRegistrationDocuments: "Tài liệu đăng ký xe",
      reviewAndApproveCarRegistrationDocuments: "Xem xét và phê duyệt tài liệu đăng ký xe",
      searchDocuments: "Tìm kiếm tài liệu...",
      documents: "tài liệu",
      userFullName: "Tên đầy đủ người dùng",
      carInfo: "Thông tin xe",
      documentImage: "Hình ảnh tài liệu",
      submittedDate: "Ngày nộp",
      status: "Trạng thái",
      registrationDocumentDetails: "Chi tiết tài liệu đăng ký",
      documentImages: "Hình ảnh tài liệu",
      noDocumentImagesAvailable: "Không có hình ảnh tài liệu",
      approveRegistrationDocument: "Phê duyệt tài liệu đăng ký",
      areYouSureApprove: "Bạn có chắc chắn muốn phê duyệt tài liệu đăng ký này?",
      user: "Người dùng",
      car: "Xe",
      carId: "Mã xe",
      confirm: "Xác nhận",
      cancel: "Hủy",
      approving: "Đang phê duyệt...",
      approve: "Phê duyệt",
      rejecting: "Đang từ chối...",
      reject: "Từ chối",
      errorLoadingDocuments: "Lỗi khi tải tài liệu",
      retry: "Thử lại",
      noDocumentsFound: "Không tìm thấy tài liệu",
      areYouSureReject: "Bạn có chắc chắn muốn từ chối tài liệu đăng ký này?",
      rejectRegistrationDocument: "Từ chối tài liệu đăng ký",
      failedToApproveRegistrationDocument: "Thất bại khi phê duyệt tài liệu đăng ký",
      registrationDocumentApprovedSuccessfully: "Phê duyệt tài liệu đăng ký thành công",
      failedToRejectRegistrationDocument: "Thất bại khi từ chối tài liệu đăng ký",
      registrationDocumentRejectedSuccessfully: "Từ chối tài liệu đăng ký thành công",
      denied: "Từ chối",
      //needmanualcheck:"Need Manual Check"
      statusNeedManualCheck: "Cần kiểm tra lại",

      customerSuspendedSuccessfully: "Khách hàng đã bị ban thành công!",
      failedToSuspendCustomer: "Không thể ban khách hàng",
      behaviourScore: "Điểm hành vi",
      tryAdjustingFilters: "Thử điều chỉnh bộ lọc",
      noCustomersFound: "Không tìm thấy khách hàng",
      noDataToExport: "Không có dữ liệu để Export",
      exportSuccessful: "Export thành công",
      exportFailed: "Export thất bại",
    }
  }
};