// Booking Management feature specific translations
export const rentalHistoryTranslate = {
  en: {
    translation: {
      // Rental History Component
      "rentalHistory.title": "Rental History",
      "rentalHistory.subtitle": "Browse rental history, filter by car and date",
      "rentalHistory.exportReport": "Export Report",
      "rentalHistory.searchPlaceholder": "Search by booking ID, customer or car",
      "rentalHistory.allCars": "All Cars",
      "rentalHistory.allStatuses": "All Statuses",
      "rentalHistory.allBookingFeeStatuses": "All Booking Fee Statuses",
      "rentalHistory.allRentalFeeStatuses": "All Rental Fee Statuses",
      "rentalHistory.allAdditionalFeeStatuses": "All Additional Fee Statuses",
      "rentalHistory.allExtendBookingFeeStatuses": "All Extend Booking Fee Statuses",
      "rentalHistory.confirmed": "Confirmed",
      "rentalHistory.completed": "Completed",
      "rentalHistory.cancelled": "Cancelled",
      "rentalHistory.paid": "Success",
      "rentalHistory.pending": "Pending",
      "rentalHistory.refunded": "Refunded",
      "rentalHistory.failed": "Failed",
      "rentalHistory.customDateRange": "Custom Date Range:",
      "rentalHistory.from": "From:",
      "rentalHistory.to": "To:",
      "rentalHistory.clearDates": "Clear Dates",
      "rentalHistory.invoiceCode": "Invoice Code",
      "rentalHistory.carInfo": "Car Information",
      "rentalHistory.customer": "Customer",
      "rentalHistory.rentalTime": "Rental Time",
      "rentalHistory.duration": "Duration",
      "rentalHistory.amount": "Amount",
      "rentalHistory.bookingFeeStatus": "Booking Fee Status",
      "rentalHistory.rentalFeeStatus": "Rental Fee Status",
      "rentalHistory.additionalFeeStatus": "Additional Fee Status",
      "rentalHistory.extendBookingFeeStatus": "Extend Booking Fee Status",
      "rentalHistory.bookingStatus": "Booking Status",
      "rentalHistory.actions": "Actions",
      "rentalHistory.viewDetails": "View Details",
      "rentalHistory.noRentalHistory": "No rental history found",
      "rentalHistory.loadingRentalHistory": "Loading rental history...",
      "rentalHistory.errorLoadingRentalHistory": "Unable to load rental history. Please try again later.",
      "rentalHistory.tryAgain": "Try Again",
      "rentalHistory.days": "days",
      "rentalHistory.bookingFee": "Booking Fee",
      "rentalHistory.rentalFee": "Rental Fee",
      "rentalHistory.additionalFee": "Additional Fee",
      "rentalHistory.extendBookingFee": "Extend Booking Fee",
      "rentalHistory.noPaymentMethod": "No payment method",
      "rentalHistory.extend":"Extend Rent",
      // Rental Details Modal //{t('rentalHistory.extend')}
      "rentalHistory.rentalDetails": "Rental Details",
      "rentalHistory.vehicleInformation": "Vehicle Information",
      "rentalHistory.customerInformation": "Customer Information",
      "rentalHistory.vehicleName": "Vehicle Name",
      "rentalHistory.name": "Name",
      "rentalHistory.licensePlateNumber": "License Plate Number",
      "rentalHistory.email": "Email",
      "rentalHistory.vehicleCode": "Vehicle Code",
      "rentalHistory.phoneNumber": "Phone Number",
      "rentalHistory.rentalDuration": "Rental Duration",
      "rentalHistory.startDate": "Start Date",
      "rentalHistory.endDate": "End Date",
      "rentalHistory.pickupCar": "Pick-up car",
      "rentalHistory.returnCar": "Return the car",
      "rentalHistory.renewRental": "Renew Rental",
      "rentalHistory.financialInformation": "Financial Information",
      "rentalHistory.totalBill": "Total Bill",
      "rentalHistory.totalPaid": "Total Paid",
      "rentalHistory.remaining": "Remaining",
      "rentalHistory.depositFee": "Deposit Fee",
      "rentalHistory.renewalFee": "Renewal Fee",
      "rentalHistory.amount": "Amount",
      "rentalHistory.status": "Status",
      "rentalHistory.method": "Method",
      "rentalHistory.currentStatus": "Current Status",
      "rentalHistory.bookingCreationDate": "Booking Creation Date",
      "rentalHistory.notes": "Notes",
      "rentalHistory.additionalInformation": "Additional Information",
      "rentalHistory.print": "Print",
      "rentalHistory.pdf": "PDF",
      "rentalHistory.printReceipt": "Print Receipt",
      "rentalHistory.exportPDF": "Export PDF",
      "rentalHistory.receiptNotAvailable": "Receipt not available for cancelled bookings",
      "rentalHistory.cannotPrintCancelled": "Cannot print receipt for cancelled booking",
      "rentalHistory.cannotExportCancelled": "Cannot export PDF for cancelled booking",
      "rentalHistory.dailyRate": "Daily rate",
    }
  },
  vi: {
    translation: {

      // Rental History Component
      "rentalHistory.title": "Lịch sử thuê xe",
      "rentalHistory.subtitle": "Duyệt lịch sử thuê xe, lọc theo xe và ngày tháng",
      "rentalHistory.exportReport": "Xuất báo cáo",
      "rentalHistory.searchPlaceholder": "Tìm kiếm theo mã đặt xe, khách hàng hoặc xe",
      "rentalHistory.allCars": "Tất cả xe",
      "rentalHistory.allStatuses": "Tất cả trạng thái",
      "rentalHistory.allBookingFeeStatuses": "Tất cả trạng thái phí đặt cọc",
      "rentalHistory.allRentalFeeStatuses": "Tất cả trạng thái phí thuê xe",
      "rentalHistory.allAdditionalFeeStatuses": "Tất cả trạng thái phí bổ sung",
      "rentalHistory.allExtendBookingFeeStatuses": "Tất cả trạng thái phí gia hạn",
      "rentalHistory.confirmed": "Đã xác nhận",
      "rentalHistory.completed": "Hoàn thành",
      "rentalHistory.cancelled": "Đã hủy",
      "rentalHistory.paid": "Đã thanh toán",
      "rentalHistory.pending": "Chờ thanh toán",
      "rentalHistory.refunded": "Đã hoàn tiền",
      "rentalHistory.failed": "Thất bại",
      "rentalHistory.customDateRange": "Khoảng thời gian tùy chỉnh:",
      "rentalHistory.from": "Từ:",
      "rentalHistory.to": "Đến:",
      "rentalHistory.clearDates": "Xóa ngày",
      "rentalHistory.invoiceCode": "Mã hóa đơn",
      "rentalHistory.carInfo": "Thông tin xe",
      "rentalHistory.customer": "Khách hàng",
      "rentalHistory.rentalTime": "Thời gian thuê",
      "rentalHistory.duration": "Thời lượng",
      "rentalHistory.amount": "Số tiền",
      "rentalHistory.bookingFeeStatus": "Trạng thái phí đặt cọc",
      "rentalHistory.rentalFeeStatus": "Trạng thái phí thuê xe",
      "rentalHistory.additionalFeeStatus": "Trạng thái phí bổ sung",
      "rentalHistory.extendBookingFeeStatus": "Trạng thái phí gia hạn",
      "rentalHistory.bookingStatus": "Trạng thái đặt xe",
      "rentalHistory.actions": "Thao tác",
      "rentalHistory.viewDetails": "Xem chi tiết",
      "rentalHistory.noRentalHistory": "Không tìm thấy lịch sử thuê xe",
      "rentalHistory.loadingRentalHistory": "Đang tải lịch sử thuê xe...",
      "rentalHistory.errorLoadingRentalHistory": "Không thể tải lịch sử thuê xe. Vui lòng thử lại sau.",
      "rentalHistory.tryAgain": "Thử lại",
      "rentalHistory.days": "ngày",
      "rentalHistory.bookingFee": "Đặt cọc",
      "rentalHistory.rentalFee": "Thuê xe",
      "rentalHistory.additionalFee": "Phí bổ sung",
      "rentalHistory.extendBookingFee": "Phí gia hạn",
      "rentalHistory.noPaymentMethod": "Chưa có phương thức thanh toán",
      "rentalHistory.extend":"Gia hạn",
      // Rental Details Modal
      "rentalHistory.rentalDetails": "Chi tiết thuê xe",
      "rentalHistory.vehicleInformation": "Thông tin xe",
      "rentalHistory.customerInformation": "Thông tin khách hàng",
      "rentalHistory.vehicleName": "Tên xe",
      "rentalHistory.name": "Tên",
      "rentalHistory.licensePlateNumber": "Biển số xe",
      "rentalHistory.email": "Email",
      "rentalHistory.vehicleCode": "Mã xe",
      "rentalHistory.phoneNumber": "Số điện thoại",
      "rentalHistory.rentalDuration": "Thời gian thuê xe",
      "rentalHistory.startDate": "Ngày bắt đầu",
      "rentalHistory.endDate": "Ngày kết thúc",
      "rentalHistory.pickupCar": "Nhận xe",
      "rentalHistory.returnCar": "Trả xe",
      "rentalHistory.renewRental": "Gia hạn thời gian thuê",
      "rentalHistory.financialInformation": "Thông tin tài chính",
      "rentalHistory.totalBill": "Tổng hóa đơn",
      "rentalHistory.totalPaid": "Tổng đã thanh toán",
      "rentalHistory.remaining": "Còn lại",
      "rentalHistory.depositFee": "Phí đặt cọc",
      "rentalHistory.renewalFee": "Phí gia hạn",
      "rentalHistory.amount": "Số tiền",
      "rentalHistory.status": "Trạng thái",
      "rentalHistory.method": "Phương thức",
      "rentalHistory.currentStatus": "Trạng thái hiện tại",
      "rentalHistory.bookingCreationDate": "Ngày tạo đặt xe",
      "rentalHistory.notes": "Ghi chú",
      "rentalHistory.additionalInformation": "Thông tin bổ sung",
      "rentalHistory.print": "In",
      "rentalHistory.pdf": "PDF",
      "rentalHistory.printReceipt": "In hóa đơn",
      "rentalHistory.exportPDF": "Xuất PDF",
      "rentalHistory.receiptNotAvailable": "Hóa đơn không khả dụng cho đặt xe đã hủy",
      "rentalHistory.cannotPrintCancelled": "Không thể in hóa đơn cho đặt xe đã hủy",
      "rentalHistory.cannotExportCancelled": "Không thể xuất PDF cho đặt xe đã hủy",
      "rentalHistory.dailyRate": "Giá thuê hàng ngày",
    }
  }
};