// Booking Management feature specific translations
export const rentalHistoryTranslate = {
  en: {
    translation: {
      // Rental History Component
      "rentalHistory.title": "Rental History",
      "rentalHistory.subtitle": "Browse rental history, filter by car and date",
      "rentalHistory.exportReport": "Export Report",
      "rentalHistory.searchPlaceholder": "Search by booking ID, customer or car",
      "rentalHistory.allCars": "All Cars",
      "rentalHistory.allStatuses": "All Statuses",
      "rentalHistory.allBookingFeeStatuses": "All Booking Fee Statuses",
      "rentalHistory.allRentalFeeStatuses": "All Rental Fee Statuses",
      "rentalHistory.allAdditionalFeeStatuses": "All Additional Fee Statuses",
      "rentalHistory.confirmed": "Confirmed",
      "rentalHistory.completed": "Completed",
      "rentalHistory.cancelled": "Cancelled",
      "rentalHistory.paid": "Paid",
      "rentalHistory.pending": "Pending",
      "rentalHistory.refunded": "Refunded",
      "rentalHistory.failed": "Failed",
      "rentalHistory.customDateRange": "Custom Date Range:",
      "rentalHistory.from": "From:",
      "rentalHistory.to": "To:",
      "rentalHistory.clearDates": "Clear Dates",
      "rentalHistory.invoiceCode": "Invoice Code",
      "rentalHistory.carInfo": "Car Information",
      "rentalHistory.customer": "Customer",
      "rentalHistory.rentalTime": "Rental Time",
      "rentalHistory.duration": "Duration",
      "rentalHistory.amount": "Amount",
      "rentalHistory.bookingFeeStatus": "Booking Fee Status",
      "rentalHistory.rentalFeeStatus": "Rental Fee Status",
      "rentalHistory.additionalFeeStatus": "Additional Fee Status",
      "rentalHistory.bookingStatus": "Booking Status",
      "rentalHistory.actions": "Actions",
      "rentalHistory.viewDetails": "View Details",
      "rentalHistory.noRentalHistory": "No rental history found",
      "rentalHistory.loadingRentalHistory": "Loading rental history...",
      "rentalHistory.errorLoadingRentalHistory": "Unable to load rental history. Please try again later.",
      "rentalHistory.tryAgain": "Try Again",
      "rentalHistory.days": "days",
      "rentalHistory.bookingFee": "Booking Fee",
      "rentalHistory.rentalFee": "Rental Fee",
      "rentalHistory.additionalFee": "Additional Fee",
      "rentalHistory.noPaymentMethod": "No payment method",
    }
  },
  vi: {
    translation: {

      // Rental History Component
      "rentalHistory.title": "Lịch sử thuê xe",
      "rentalHistory.subtitle": "Duyệt lịch sử thuê xe, lọc theo xe và ngày tháng",
      "rentalHistory.exportReport": "Xuất báo cáo",
      "rentalHistory.searchPlaceholder": "Tìm kiếm theo mã đặt xe, khách hàng hoặc xe",
      "rentalHistory.allCars": "Tất cả xe",
      "rentalHistory.allStatuses": "Tất cả trạng thái",
      "rentalHistory.allBookingFeeStatuses": "Tất cả trạng thái phí đặt cọc",
      "rentalHistory.allRentalFeeStatuses": "Tất cả trạng thái phí thuê xe",
      "rentalHistory.allAdditionalFeeStatuses": "Tất cả trạng thái phí bổ sung",
      "rentalHistory.confirmed": "Đã xác nhận",
      "rentalHistory.completed": "Hoàn thành",
      "rentalHistory.cancelled": "Đã hủy",
      "rentalHistory.paid": "Đã thanh toán",
      "rentalHistory.pending": "Chờ thanh toán",
      "rentalHistory.refunded": "Đã hoàn tiền",
      "rentalHistory.failed": "Thất bại",
      "rentalHistory.customDateRange": "Khoảng thời gian tùy chỉnh:",
      "rentalHistory.from": "Từ:",
      "rentalHistory.to": "Đến:",
      "rentalHistory.clearDates": "Xóa ngày",
      "rentalHistory.invoiceCode": "Mã hóa đơn",
      "rentalHistory.carInfo": "Thông tin xe",
      "rentalHistory.customer": "Khách hàng",
      "rentalHistory.rentalTime": "Thời gian thuê",
      "rentalHistory.duration": "Thời lượng",
      "rentalHistory.amount": "Số tiền",
      "rentalHistory.bookingFeeStatus": "Trạng thái phí đặt cọc",
      "rentalHistory.rentalFeeStatus": "Trạng thái phí thuê xe",
      "rentalHistory.additionalFeeStatus": "Trạng thái phí bổ sung",
      "rentalHistory.bookingStatus": "Trạng thái đặt xe",
      "rentalHistory.actions": "Thao tác",
      "rentalHistory.viewDetails": "Xem chi tiết",
      "rentalHistory.noRentalHistory": "Không tìm thấy lịch sử thuê xe",
      "rentalHistory.loadingRentalHistory": "Đang tải lịch sử thuê xe...",
      "rentalHistory.errorLoadingRentalHistory": "Không thể tải lịch sử thuê xe. Vui lòng thử lại sau.",
      "rentalHistory.tryAgain": "Thử lại",
      "rentalHistory.days": "ngày",
      "rentalHistory.bookingFee": "Đặt cọc",
      "rentalHistory.rentalFee": "Thuê xe",
      "rentalHistory.additionalFee": "Phí bổ sung",
      "rentalHistory.noPaymentMethod": "Chưa có phương thức thanh toán",
    }
  }
};