export const carTranslate = {
  en: {
    translation: {
      // Car Registration Validation
      manufacturerRequired: "Brand is required",
      modelRequired: "Model is required",
      numberOfSeatsRequired: "Number of seats is required",
      yearOfManufactureRequired: "Year of manufacture is required",
      transmissionRequired: "Transmission is required",
      fuelTypeRequired: "Fuel type is required",
      invalidNumberOfSeats: "Number of seats must be a positive number",
      invalidYearOfManufacture: "Year of manufacture must be between 1900 and {{currentYear}}",

      // Car Detail Rev
      viewAllPhotos: "View all photos",
      trips: "trips",
      noCollateral: "NO COLLATERAL",
      deliveryAvailable: "Delivery available",
      features: "Features",
      description: "Description",
      seeMore: "See more",
      amenities: "Amenities",
      map: "Map",
      bluetooth: "Bluetooth",
      camera360: "Camera 360",
      cameraBlindSpot: "Blind spot camera",
      dashCam: "Dash cam",
      backupCamera: "Backup camera",
      tirePressureSensor: "Tire pressure sensor",
      collisionSensor: "Collision sensor",
      speedWarning: "Speed warning",
      gpsTracking: "GPS tracking",
      usbPort: "USB port",
      spareTire: "Spare tire",
      dvdScreen: "DVD screen",
      etc: "ETC",
      airbag: "Airbag",
      rentalDocuments: "Rental documents",
      licenseAndId: "License (verify) & ID (photo with VNeID)",
      licenseAndPassport: "License (verify) & Passport (hold)",
      collateral: "Collateral",
      noCollateralRequired: "No cash or motorcycle collateral required",
      terms: "Terms",
      termsOtherRules: "Other rules:",
      termsUseProper: "- Use vehicle for proper purposes",
      termsNoIllegal: "- Do not use rental vehicle for illegal purposes",
      termsNoPawn: "- Do not use rental vehicle as collateral or pawn",
      termsNoSmoking: "- No smoking, spitting gum, littering in vehicle",
      termsNoExplosives: "- Do not transport prohibited or flammable goods",
      termsNoStrongSmell: "- Do not transport fruits or strong-smelling food in vehicle",
      cancellationPolicy: "Cancellation policy",
      cancellationTime: "Cancellation Time",
      cancellationFee: "Cancellation Fee",
      within1Hour: "Within 1h after Booking",
      free: "Free",
      moreThan7Days: "More than 7 Days Before Trip",
      after1HourBooking: "(After 1h Booking)",
      minValueTrip: "10% value (minimum trip)",
      within7Days: "Within 7 Days Before Trip",
      minValue40: "40% value (minimum trip)",
      cancellationNote1: "* Customers will be charged a cancellation fee if unable to travel at the booked time, except for force majeure (accidents, natural disasters, epidemics, flight cancellations/delays, public transport malfunctions, etc.)",
      cancellationNote2: "* If customer does not pick up vehicle within 1h from rental start time (without prior notice to owner)",
      cancellationNote3: "* Owner does not deliver vehicle at trip start time (without prior notice to renter) (100% trip value)",
      cancellationNote4: "* Depending on specific circumstances, Morrent will consider supporting customers with partial or full refund if trip is cancelled due to force majeure. In this case, customers need to contact Morrent's customer support team for assistance.",
      vehicleLocation: "Vehicle location",
      specificAddressAfterBooking: "Specific address will be displayed after successful booking",
      viewMap: "View map",
      responseRate: "Response rate",
      acceptanceRate: "Acceptance rate",
      minutes: "minutes",
      ownerBadgeText: "5 owner with fast response time, high acceptance rate, competitive pricing & excellent service rated by customers",
      ratings: "ratings",
      promoCode: "Promo code",
      totalPrice: "Total price",
      rentCar: "RENT CAR",
      additionalFees: "Additional fees may apply",
      mileageFee: "Mileage fee",
      mileageFeeDesc: "Fee applies if travel exceeds 300km (Limit: 300km/day)",
      overtimeFee: "Overtime fee",
      overtimeFeeDesc: "Fee applies if vehicle returned late. If more than 5 hours late, additional day fee applies",
      deodorizingFee: "Deodorizing fee",
      deodorizingFeeDesc: "Fee applies when vehicle has unpleasant odor (cigarette smoke, strong-smelling food...)",
      reportCar: "Report this car",
      rentalInsurance: "Rental insurance",
      rentalInsuranceDesc: "Trip includes insurance. Customer only compensates maximum 2,000,000đ in case of unexpected incidents.",
      dailyRate: "Daily rate",
      pickupDate: "Pickup",
      dropoffDate: "Dropoff",
      pickupLocation: "Pickup location",
      selfPickup: "Self pickup",
      driverDelivery: "Delivers vehicle ",
      priceBreakdown: "Price breakdown",
      insuranceFee: "Insurance fee",
      physicalInsurance: "Physical insurance",
      driverInsurance: "Driver insurance",
      totalCost: "Total cost",
      deliveryFee: "Delivery fee",
      discount: "Discount",
      discountDesc: "Discount for daily rate",
      filesSelected: "Files Selected",
      managedByMorrent: "Managed By Morrent",
      // Additional Car Detail translations
      chooseOneOfTwo: "Choose 1 of 2 options",
      licenseAndPassportHold: "License (verify) & Passport (hold)",
      licenseAndIdVneID: "License (verify) & ID (verify with VNeID)",
      noReviews: "No reviews yet",
      loadingReviews: "Loading reviews...",
      viewMoreReviews: "View more",
      moreReviews: "reviews",
      showLess: "Show less",
      bookingFeesPayNow: "Booking Fees (15%) - Pay Now",
      remainingAmountPayAfter: "Remaining Amount - Pay After",
      totalPricePayNow: "Total Price",
      distance: "Distance",

      // Verification Modal
      verificationRequired: "Verification Required",
      verificationRequiredMessage: "You need to upload and verify your driver's license before you can rent a car.",
      uploadDriverLicense: "Upload Driver License",

      //Delivery Location Modal
      vehiclePicDeliLocation: "Vehicle Pickup and Delivery Location",
      deliveryCar: "Delivery (20,000 VND/km)",
      customAddress: "Custom Address",
      closeModal: "Close",
      inputOrTapIcon: "Enter a specific address or tap the icon to get the current location",
      airportLocation: "Airport Delivery",
      deliveryFees: "Delivery fee will be calculated based on the actual distance",
      minimum: "20.000₫/km (minimum 60.000₫)",
      changeAddress: "Change Address",
      addressConfirmation: " Address Confirmation",

      //DateAndTimePicker
      time: "Time",
      rentalPerDay: "Rental per day",
      month: "Month",
      pickUpVehicle: "Pick up vehicle",
      returnVehicle: "Return vehicle",
      pickUpTime: "Pick up time",
      returnTime: "Return time",
      rentalDuration: "Rental duration",
      days: "ngày",
      T: "T",
      next: "Next",
      estimatedPrice: "Estimated Price",
      holidaySurcharge: "holiday surcharge",
      holidayPricingNotice: "Holiday pricing applies to selected dates",
      vietnameseHoliday: "Vietnamese Holiday",
      normalDays: "Normal days",
      holidayDays: "Holiday days",
      // Month names
      january: "January",
      february: "February",
      march: "March",
      april: "April",
      may: "May",
      june: "June",
      july: "July",
      august: "August",
      september: "September",
      october: "October",
      november: "November",
      december: "December",
      // Week names
      monday: "M",
      tuesday: "T",
      wednesday: "W",
      thursday: "T",
      friday: "F",
      saturday: "S",
      sunday: "S",
      //report
      report: "Report",
      reportingCar: "Reporting Car",
      reportContent: "Report Content",
      reportTitle: "Report Title",
      describeIssue: "Describe Issue",
      reportSubmittedSuccessfully: "Report submitted successfully",
      failedToSubmitReport: "Failed to submit report",
    }
  },
  vi: {
    translation: {
      // Car Registration Validation
      manufacturerRequired: "Hãng xe là bắt buộc",
      modelRequired: "Mẫu xe là bắt buộc",
      numberOfSeatsRequired: "Số ghế là bắt buộc",
      yearOfManufactureRequired: "Năm sản xuất là bắt buộc",
      transmissionRequired: "Hộp số là bắt buộc",
      fuelTypeRequired: "Loại nhiên liệu là bắt buộc",
      invalidNumberOfSeats: "Số ghế phải là số dương",
      invalidYearOfManufacture: "Năm sản xuất phải từ 1900 đến {{currentYear}}",

      // Car Detail Rev
      viewAllPhotos: "Xem tất cả ảnh",
      trips: "chuyến",
      noCollateral: "MIỄN THẾ CHẤP",
      deliveryAvailable: "Giao xe tận nơi",
      features: "Đặc điểm",
      description: "Mô tả",
      seeMore: "Xem thêm",
      amenities: "Các tiện nghi khác",
      map: "Bản đồ",
      bluetooth: "Bluetooth",
      camera360: "Camera 360",
      cameraBlindSpot: "Camera cập lề",
      dashCam: "Camera hành trình",
      backupCamera: "Camera lùi",
      tirePressureSensor: "Cảm biến lốp",
      collisionSensor: "Cảm biến va chạm",
      speedWarning: "Cảnh báo tốc độ",
      gpsTracking: "Định vị GPS",
      usbPort: "Khe cắm USB",
      spareTire: "Lốp dự phòng",
      dvdScreen: "Màn hình DVD",
      etc: "ETC",
      airbag: "Túi khí an toàn",
      rentalDocuments: "Giấy tờ thuê xe",
      licenseAndId: "GPLX (đối chiếu) & CCCD (chụp chiếu VNeID)",
      licenseAndPassport: "GPLX (đối chiếu) & Passport (giữ lại)",
      collateral: "Tài sản thế chấp",
      noCollateralRequired: "Không yêu cầu khách thuê thế chấp Tiền mặt hoặc Xe máy",
      terms: "Điều khoản",
      termsOtherRules: "Quy định khác:",
      termsUseProper: "- Sử dụng xe đúng mục đích",
      termsNoIllegal: "- Không sử dụng xe thuê vào mục đích phi pháp, trái pháp luật",
      termsNoPawn: "- Không sử dụng xe thuê để cầm cố, thế chấp",
      termsNoSmoking: "- Không hút thuốc, nhả kẹo cao su, xả rác trong xe",
      termsNoExplosives: "- Không chở hàng quốc cấm dễ cháy nổ",
      termsNoStrongSmell: "- Không chở hoa quả, thực phẩm nặng mùi trong xe",
      cancellationPolicy: "Chính sách hủy chuyến",
      cancellationTime: "Thời điểm Hủy Chuyến",
      cancellationFee: "Phí Hủy Chuyến",
      within1Hour: "Trong vòng 1h sau Đặt Chỗ",
      free: "Miễn phí",
      moreThan7Days: "Trước Chuyến Đi >7 Ngày",
      after1HourBooking: "(Sau 1h Đặt Chỗ)",
      minValueTrip: "10% giá trị (tối thiểu đi)",
      within7Days: "Trong vòng 7 Ngày Trước Chuyến Đi",
      minValue40: "40% giá trị (tối thiểu đi)",
      cancellationNote1: "* Khách hàng thuê chuyến đi sẽ chịu phí hủy chuyến nếu như không thể đi vào thời điểm đã đặt, trừ các trường hợp bất khả kháng (tai nạn, thiên tai, dịch bệnh, hoãn/hủy chuyến bay, phương tiện vận chuyển công cộng bị trục trặc, v.v.)",
      cancellationNote2: "* Nếu khách hàng không nhận xe trong vòng 1h kể từ thời điểm bắt đầu thuê chuyến (không báo trước với chủ xe)",
      cancellationNote3: "* Chủ xe không giao xe đúng thời điểm bắt đầu chuyến đi (không báo trước với khách thuê) (100% giá trị chuyến đi)",
      cancellationNote4: "* Tùy trường hợp cụ thể, Morrent sẽ xem xét để hỗ trợ khách hàng hoàn lại một phần hoặc toàn bộ chi phí đã thanh toán nếu chuyến đi bị hủy vì những lý do bất khả kháng. Trong trường hợp này, khách hàng cần liên hệ với bộ phận hỗ trợ khách hàng của Morrent để được hỗ trợ.",
      vehicleLocation: "Vị trí xe",
      specificAddressAfterBooking: "Địa chỉ cụ thể sẽ được hiển thị sau khi đặt thuận thành công",
      viewMap: "Xem bản đồ",
      responseRate: "Tỉ lệ phản hồi",
      acceptanceRate: "Tỉ lệ đồng ý",
      minutes: "phút",
      ownerBadgeText: "Chủ xe 5 có thời gian phản hồi nhanh, tỉ lệ đồng ý cao, mức giá cạnh tranh & dịch vụ vượt trội được khách hàng đánh giá tốt từ khách hàng",
      ratings: "đánh giá",
      promoCode: "Mã khuyến mãi",
      totalPrice: "Thành tiền",
      rentCar: "CHỌN THUÊ",
      additionalFees: "Phụ phí có thể phát sinh",
      mileageFee: "Phí vượt giới hạn",
      mileageFeeDesc: "Phí phát sinh nếu lộ trình di chuyển vượt quá 300km (Giới hạn: 300km/ngày)",
      overtimeFee: "Phí quá giờ",
      overtimeFeeDesc: "Phí phát sinh nếu hoàn trả xe trễ giờ. Trường hợp trễ quá 5 giờ, phí phát sinh thêm 1 ngày",
      deodorizingFee: "Phí khử mùi",
      deodorizingFeeDesc: "Phí phát sinh khi xe có mùi khó chịu (mùi thuốc lá, thực phẩm nặng mùi...)",
      reportCar: "Báo cáo xe này",
      rentalInsurance: "Bảo hiểm thuê xe",
      rentalInsuranceDesc: "Chuyến đi có mua bảo hiểm. Khách hàng chỉ bồi thường tối đa 2.000.000đ trong trường hợp có sự cố ngoài ý muốn.",
      dailyRate: "Đơn giá thuê",
      pickupDate: "Nhận xe",
      dropoffDate: "Trả xe",
      pickupLocation: "Địa điểm giao nhận xe",
      selfPickup: "Tự tới lấy xe",
      driverDelivery: "Tài xế đưa xe tận nơi",
      priceBreakdown: "Bảng giá chi tiết",
      insuranceFee: "Bảo hiểm thuê xe",
      physicalInsurance: "Bảo hiểm thể dưỡng",
      driverInsurance: "Bảo hiểm người lái",
      totalCost: "Tổng cộng",
      deliveryFee: "Phí giao nhận xe",
      discount: "Chương trình giảm giá",
      discountDesc: "Giảm 120k cho đơn giá",
      filesSelected: "File đã chọn",
      managedByMorrent: "Managed By Morrent",
      // Additional Car Detail translations
      chooseOneOfTwo: "Chọn 1 trong 2 hình thức",
      licenseAndPassportHold: "GPLX (đối chiếu) & Passport (giữ lại)",
      licenseAndIdVneID: "GPLX (đối chiếu) & CCCD (đối chiếu VNeID)",
      noReviews: "Chưa có đánh giá nào",
      loadingReviews: "Đang tải đánh giá...",
      viewMoreReviews: "Xem thêm",
      moreReviews: "đánh giá",
      showLess: "Thu gọn",
      bookingFeesPayNow: "Phí Đặt Cọc (15%) - Thanh Toán Ngay",
      remainingAmountPayAfter: "Số Tiền Còn Lại - Thanh Toán Sau",
      totalPricePayNow: "Thành Tiền",
      distance: "Khoảng cách",

      // Verification Modal
      verificationRequired: "Yêu cầu xác minh",
      verificationRequiredMessage: "Bạn cần tải lên và xác minh bằng lái xe trước khi có thể thuê xe.",
      uploadDriverLicense: "Tải lên bằng lái xe",
      //Delivery Location Modal
      vehiclePicDeliLocation: "Địa điểm giao nhận xe",
      deliveryCar: "Giao xe tận nơi (20.000₫/km)",
      customAddress: "Địa chỉ tùy chỉnh",
      closeModal: "Đóng",
      inputOrTapIcon: "Nhập địa chỉ cụ thể hoặc nhấn biểu tượng để lấy vị trí hiện tại",
      airportLocation: "Giao xe sân bay",
      deliveryFee: "Phí giao xe sẽ được tính dựa trên khoảng cách thực tế",
      minimum: "20.000₫/km (tối thiểu 60.000₫)",
      changeAddress: "Thay đổi",
      addressConfirmation: " Xác nhận địa chỉ",
      //DateAndTimePicker
      time: "Thời gian",
      rentalPerDay: "Thuê theo ngày",
      month: "Tháng",
      pickUpVehicle: "Nhận xe",
      returnVehicle: "Trả xe",
      pickUpTime: "Thời gian nhận xe",
      returnTime: "Thời gian trả xe",
      rentalDuration: "Thời gian thuê",
      days: "ngày",
      T: "T",
      next: "Tiếp tục",
      estimatedPrice: "Giá ước tính",
      holidaySurcharge: "phụ phí ngày lễ",
      holidayPricingNotice: "Áp dụng giá ngày lễ cho các ngày đã chọn",
      vietnameseHoliday: "Ngày lễ Việt Nam",
      normalDays: "Ngày thường",
      holidayDays: "Ngày lễ",
      // Month names
      january: "Tháng 1",
      february: "Tháng 2",
      march: "Tháng 3",
      april: "Tháng 4",
      may: "Tháng 5",
      june: "Tháng 6",
      july: "Tháng 7",
      august: "Tháng 8",
      september: "Tháng 9",
      october: "Tháng 10",
      november: "Tháng 11",
      december: "Tháng 12",
      // Week names
      monday: "T2",
      tuesday: "T3",
      wednesday: "T4",
      thursday: "T5",
      friday: "T6",
      saturday: "T7",
      sunday: "CN",
      //report
      report: "Báo cáo xe",
      reportingCar: "Báo cáo xe",
      reportContent: "Nội dung báo cáo",
      reportTitle: "Tiêu đề báo cáo",
      describeIssue: "Mô tả vấn đề gặp phải",
      reportSubmittedSuccessfully: "Gửi báo cáo thành công",
      failedToSubmitReport: "Gửi báo cáo thất bại",
    }
  }
};