export const paymentOwnerTranslate = {
  en: {
    translation: {
      // Payments Component
      "payments.title": "Payments",
      "payments.subtitle": "View payment history and export receipts",
      "payments.exportAllReceipts": "Export All Receipts",
      "payments.totalReceived": "Total Received",
      "payments.paymentsPending": "Payments Pending",
      "payments.bookingFee": "Booking Fee",
      "payments.rentalFee": "Rental Fee",
      "payments.searchPlaceholder": "Search by transaction ID, booking ID or description",
      "payments.allTypes": "All Types",
      "payments.allPaymentMethods": "All Payment Methods",
      "payments.allStatuses": "All Statuses",
      "payments.allDates": "All Dates",
      "payments.showingResults": "Showing {{filtered}} of {{total}} transactions",
      "payments.transactionId": "Transaction ID",
      "payments.type": "Type",
      "payments.description": "Description",
      "payments.customerAndCar": "Customer & Car",
      "payments.amount": "Amount",
      "payments.paymentMethod": "Payment Method",
      "payments.createDate": "Create Date",
      "payments.updateDate": "Update Date",
      "payments.status": "Status",
      "payments.actions": "Actions",
      "payments.viewDetails": "View Details",
      "payments.exportReceipt": "Export Receipt",
      "payments.noPaymentsFound": "No payments found",
      "payments.loadingPayments": "Loading payments...",
      "payments.errorLoadingPayments": "Unable to load payment list. Please try again later.",
      "payments.tryAgain": "Try Again",
      "payments.bookingFeeType": "Booking Fee",
      "payments.rentalFeeType": "Rental Fee",
      "payments.invoice": "Invoice",
      "payments.transactionDetails": "Transaction Details - {{transactionId}}",
      "payments.paymentInfo": "Payment Information",
      "payments.invoiceCode": "Invoice Code",
      "payments.customerName": "Customer Name",
      "payments.rentalCar": "Rental Car",
      "payments.amountDetails": "Amount Details",
      "payments.amountReceived": "Amount Received",
      "payments.notes": "Notes",
      "payments.close": "Close",
      "payments.receipt": "PAYMENT RECEIPT",
      "payments.receiptSeparator": "=====================================",
      "payments.receiptTransactionId": "Transaction ID: {{transactionId}}",
      "payments.receiptDate": "Date: {{date}}",
      "payments.receiptType": "Type: {{type}}",
      "payments.receiptCustomer": "Customer: {{customerName}}",
      "payments.receiptCar": "Car: {{carName}}",
      "payments.receiptAmount": "Amount: {{amount}}",
      "payments.receiptPaymentMethod": "Payment Method: {{paymentMethod}}",
      "payments.receiptStatus": "Status: {{status}}",
      "payments.receiptDescription": "Description: {{description}}",

    }
  },
  vi: {
    translation: {
      // Payments Component
      "payments.title": "Thanh toán",
      "payments.subtitle": "Xem lịch sử thanh toán và xuất hóa đơn",
      "payments.exportAllReceipts": "Xuất tất cả hóa đơn",
      "payments.totalReceived": "Tổng đã nhận",
      "payments.paymentsPending": "Thanh toán chờ xử lý",
      "payments.bookingFee": "Phí đặt cọc",
      "payments.rentalFee": "Phí thuê xe",
      "payments.searchPlaceholder": "Tìm kiếm theo mã giao dịch, mã đặt xe hoặc khách hàng",
      "payments.allTypes": "Tất cả loại",
      "payments.allPaymentMethods": "Tất cả phương thức",
      "payments.allStatuses": "Tất cả trạng thái",
      "payments.allDates": "Tất cả ngày",
      "payments.showingResults": "Hiển thị {{filtered}} trong tổng số {{total}} giao dịch",
      "payments.transactionId": "Mã giao dịch",
      "payments.type": "Loại",
      "payments.description": "Mô tả",
      "payments.customerAndCar": "Khách hàng & Xe",
      "payments.amount": "Số tiền",
      "payments.paymentMethod": "Phương thức",
      "payments.createDate": "Ngày tạo",
      "payments.updateDate": "Ngày cập nhập",
      "payments.status": "Trạng thái",
      "payments.actions": "Thao tác",
      "payments.viewDetails": "Xem chi tiết",
      "payments.exportReceipt": "Xuất hóa đơn",
      "payments.noPaymentsFound": "Không tìm thấy thanh toán nào",
      "payments.loadingPayments": "Đang tải thanh toán...",
      "payments.errorLoadingPayments": "Không thể tải danh sách thanh toán. Vui lòng thử lại sau.",
      "payments.tryAgain": "Thử lại",
      "payments.bookingFeeType": "Phí đặt cọc",
      "payments.rentalFeeType": "Phí thuê xe",
      "payments.invoice": "Hóa đơn",
      "payments.transactionDetails": "Chi tiết giao dịch - {{transactionId}}",
      "payments.paymentInfo": "Thông tin thanh toán",
      "payments.invoiceCode": "Mã hóa đơn",
      "payments.customerName": "Tên khách hàng",
      "payments.rentalCar": "Xe thuê",
      "payments.amountDetails": "Chi tiết số tiền",
      "payments.amountReceived": "Số tiền đã nhận",
      "payments.notes": "Ghi chú",
      "payments.close": "Đóng",
      "payments.receipt": "HÓA ĐƠN THANH TOÁN",
      "payments.receiptSeparator": "=====================================",
      "payments.receiptTransactionId": "Mã giao dịch: {{transactionId}}",
      "payments.receiptDate": "Ngày: {{date}}",
      "payments.receiptType": "Loại: {{type}}",
      "payments.receiptCustomer": "Khách hàng: {{customerName}}",
      "payments.receiptCar": "Xe: {{carName}}",
      "payments.receiptAmount": "Số tiền: {{amount}}",
      "payments.receiptPaymentMethod": "Phương thức thanh toán: {{paymentMethod}}",
      "payments.receiptStatus": "Trạng thái: {{status}}",
      "payments.receiptDescription": "Mô tả: {{description}}",
    }
  }
};