// Booking Management feature specific translations
export const maintenanceScheduleTranslate = {
  en: {
    translation: {
      // Maintenance Schedule Component
      "maintenanceSchedule.title": "Maintenance Schedule",
      "maintenanceSchedule.subtitle": "Track maintenance schedules and view notifications for each vehicle",
      "maintenanceSchedule.exportReport": "Export Report",
      "maintenanceSchedule.addMaintenanceRecord": "Add Maintenance Record",
      "maintenanceSchedule.searchPlaceholder": "Search by car name, license plate or ID",
      "maintenanceSchedule.allStatuses": "All Statuses",
      "maintenanceSchedule.overdue": "Overdue",
      "maintenanceSchedule.due": "Due",
      "maintenanceSchedule.upcoming": "Upcoming",
      "maintenanceSchedule.completed": "Completed",
      "maintenanceSchedule.showingResults": "Showing {{filtered}} of {{total}} vehicles",
      "maintenanceSchedule.carInfo": "Car Information",
      "maintenanceSchedule.maintenanceDate": "Maintenance Date",
      "maintenanceSchedule.maintenanceTime": "Maintenance Time",
      "maintenanceSchedule.maintenanceType": "Maintenance Type",
      "maintenanceSchedule.status": "Status",
      "maintenanceSchedule.priority": "Priority",
      "maintenanceSchedule.actions": "Actions",
      "maintenanceSchedule.fromTo": "From {{start}} to {{end}}",
      "maintenanceSchedule.timeFromTo": "From {{start}}H to {{end}}H",
      "maintenanceSchedule.high": "High",
      "maintenanceSchedule.medium": "Medium",
      "maintenanceSchedule.low": "Low",
      "maintenanceSchedule.view": "View",
      "maintenanceSchedule.schedule": "Schedule",
      "maintenanceSchedule.complete": "Complete",
      "maintenanceSchedule.previous": "Previous",
      "maintenanceSchedule.next": "Next",
      "maintenanceSchedule.scheduleMaintenanceTitle": "Schedule Maintenance",
      "maintenanceSchedule.titlePlaceholder": "e.g. Oil change, Tire rotation",
      "maintenanceSchedule.location": "Location",
      "maintenanceSchedule.locationPlaceholder": "e.g. Main service center",
      "maintenanceSchedule.startDate": "Start Date",
      "maintenanceSchedule.endDate": "End Date",
      "maintenanceSchedule.notes": "Notes",
      "maintenanceSchedule.notesPlaceholder": "Additional notes about the maintenance...",
      "maintenanceSchedule.cancel": "Cancel",
      "maintenanceSchedule.creating": "Creating...",
      "maintenanceSchedule.createSchedule": "Create Schedule",
      "maintenanceSchedule.maintenanceDetails": "Maintenance Details",
      "maintenanceSchedule.carName": "Car Name",
      "maintenanceSchedule.licensePlate": "License Plate",
      "maintenanceSchedule.currentMileage": "Current Mileage",
      "maintenanceSchedule.lastMaintenanceDate": "Last Maintenance Date",
      "maintenanceSchedule.nextMaintenanceDate": "Next Maintenance Date",
      "maintenanceSchedule.priorityLevel": "Priority level",
      "maintenanceSchedule.scheduleMaintenance": "Schedule Maintenance",
      "maintenanceSchedule.markAsCompleted": "Mark as Completed",
      "maintenanceSchedule.unknownCarModel": "Unknown Car Model",
      "maintenanceSchedule.periodicMaintenance": "Periodic Maintenance",
      "maintenanceSchedule.needsMaintenance": "Needs Maintenance",
      "maintenanceSchedule.errorLoadingSchedules": "Unable to load maintenance schedules. Please try again later.",
      "maintenanceSchedule.scheduleCreatedSuccessfully": "Maintenance schedule created successfully!",
      "maintenanceSchedule.errorCreatingSchedule": "Unable to create maintenance schedule. Please try again.",
      "maintenanceSchedule.loadingSchedules": "Loading maintenance schedules...",
      "maintenanceSchedule.tryAgain": "Try Again",
    }
  },
  vi: {
    translation: {
      // Maintenance Schedule Component
      "maintenanceSchedule.title": "Lịch Bảo Dưỡng",
      "maintenanceSchedule.subtitle": "Theo dõi lịch bảo dưỡng và xem thông báo cho từng xe",
      "maintenanceSchedule.exportReport": "Xuất Báo Cáo",
      "maintenanceSchedule.addMaintenanceRecord": "Thêm Bản Ghi Bảo Dưỡng",
      "maintenanceSchedule.searchPlaceholder": "Tìm kiếm theo tên xe, biển số hoặc ID",
      "maintenanceSchedule.allStatuses": "Tất Cả Trạng Thái",
      "maintenanceSchedule.overdue": "Quá Hạn",
      "maintenanceSchedule.due": "Đến Hạn",
      "maintenanceSchedule.upcoming": "Sắp Tới",
      "maintenanceSchedule.completed": "Hoàn Thành",
      "maintenanceSchedule.showingResults": "Hiển thị {{filtered}} trong tổng số {{total}} xe",
      "maintenanceSchedule.carInfo": "Thông Tin Xe",
      "maintenanceSchedule.maintenanceDate": "Ngày Bảo Dưỡng",
      "maintenanceSchedule.maintenanceTime": "Thời Gian Bảo Dưỡng",
      "maintenanceSchedule.maintenanceType": "Loại Bảo Dưỡng",
      "maintenanceSchedule.status": "Trạng Thái",
      "maintenanceSchedule.priority": "Độ Ưu Tiên",
      "maintenanceSchedule.actions": "Thao Tác",
      "maintenanceSchedule.fromTo": "Từ {{start}} đến {{end}}",
      "maintenanceSchedule.timeFromTo": "Từ {{start}}H đến {{end}}H",
      "maintenanceSchedule.high": "Cao",
      "maintenanceSchedule.medium": "Trung Bình",
      "maintenanceSchedule.low": "Thấp",
      "maintenanceSchedule.view": "Xem",
      "maintenanceSchedule.schedule": "Lên Lịch",
      "maintenanceSchedule.complete": "Hoàn Thành",
      "maintenanceSchedule.previous": "Trước",
      "maintenanceSchedule.next": "Sau",
      "maintenanceSchedule.scheduleMaintenanceTitle": "Lên Lịch Bảo Dưỡng",
      "maintenanceSchedule.titlePlaceholder": "VD: Thay dầu, Xoay lốp",
      "maintenanceSchedule.location": "Địa Điểm",
      "maintenanceSchedule.locationPlaceholder": "VD: Trung tâm bảo dưỡng chính",
      "maintenanceSchedule.startDate": "Ngày Bắt Đầu",
      "maintenanceSchedule.endDate": "Ngày Kết Thúc",
      "maintenanceSchedule.notes": "Ghi Chú",
      "maintenanceSchedule.notesPlaceholder": "Ghi chú bổ sung về việc bảo dưỡng...",
      "maintenanceSchedule.cancel": "Hủy",
      "maintenanceSchedule.creating": "Đang Tạo...",
      "maintenanceSchedule.createSchedule": "Tạo Lịch",
      "maintenanceSchedule.maintenanceDetails": "Chi Tiết Bảo Dưỡng",
      "maintenanceSchedule.carName": "Tên Xe",
      "maintenanceSchedule.licensePlate": "Biển Số",
      "maintenanceSchedule.currentMileage": "Số Km Hiện Tại",
      "maintenanceSchedule.lastMaintenanceDate": "Ngày Bảo Dưỡng Cuối",
      "maintenanceSchedule.nextMaintenanceDate": "Ngày Bảo Dưỡng Tiếp Theo",
      "maintenanceSchedule.priorityLevel": "Độ ưu tiên",
      "maintenanceSchedule.scheduleMaintenance": "Lên Lịch Bảo Dưỡng",
      "maintenanceSchedule.markAsCompleted": "Đánh Dấu Hoàn Thành",
      "maintenanceSchedule.unknownCarModel": "Mẫu Xe Không Xác Định",
      "maintenanceSchedule.periodicMaintenance": "Bảo Dưỡng Định Kỳ",
      "maintenanceSchedule.needsMaintenance": "Cần Bảo Dưỡng",
      "maintenanceSchedule.errorLoadingSchedules": "Không thể tải lịch bảo dưỡng. Vui lòng thử lại sau.",
      "maintenanceSchedule.scheduleCreatedSuccessfully": "Tạo lịch bảo dưỡng thành công!",
      "maintenanceSchedule.errorCreatingSchedule": "Không thể tạo lịch bảo dưỡng. Vui lòng thử lại.",
      "maintenanceSchedule.loadingSchedules": "Đang tải lịch bảo dưỡng...",
      "maintenanceSchedule.tryAgain": "Thử Lại",
    }
  }
};