export const commonTranslate = {
  en: {
    translation: {
      // NavBar
      search: "Searching",
      signIn: "Sign In",
      signUp: "Sign Up",
      notification: "Notification",
      noNotifications: "No notifications",
      bookingSuccessful: "Booking successful",
      unread: "unread",
      viewAllNotifications: "View all notifications",
      loading: "Loading...",

      // Filters
      filters: "Filters",
      carName: "Car name",
      carNamePlaceholder: "e.g. Nissan, CR-V",
      minPrice: "Min price",
      maxPrice: "Max price",
      fuelType: "Fuel type",
      seats: "Seats",
      any: "Any",
      electric: "Electric",
      hybrid: "Hybrid",
      gasoline: "Gasoline",
      diesel: "Diesel",
      cancel: "Cancel",
      apply: "Apply",

      // HomePage - Hero Section
      heroTitle: "The Best Platform for Car Rental",
      heroSubtitle: "Ease of doing a car rental safely and reliably. Of course at a low price.",
      heroTitle2: "Easy way to rent a car at a low price",
      heroSubtitle2: "Providing cheap car rental services and safe and comfortable facilities.",
      rentalCar: "Rental Car",

      // HomePage - Search Section
      pickUp: "Pick-up",
      dropOff: "Drop - Off",
      location: "Location",
      pickYourLocation: "Pick your location",
      selectCity: "Select your city",
      hoChiMinhCity: "Ho Chi Minh City",
      hanoi: "Hanoi",
      daNang: "Da Nang",
      date: "Date",
      selectDate: "Select your date",
      today: "Today",
      tomorrow: "Tomorrow",
      nextWeek: "Next week",
      time: "Time",
      selectTime: "Select your time",
      rentalPeriod: "Rental Period",
      loadingCars: "Loading cars...",
      errorLoadingCars: "Error loading cars:",
      // HomePage - Car Sections
      popularCar: "Popular Car",
      recommendationCar: "Recommendation Car",
      viewAll: "View All",
      rentNow: "Rent Now",
      perDay: "/day",
      showMoreCar: "Show more car",
      car: "Car",

      // Car Card
      manual: "Manual",
      automatic: "Automatic",
      people: "People",
      person: "Person",
      Gasoline: "Gasoline",
      Diesel: "Diesel",
      Electric: "Electric",
      // Auth - Login
      logIn: "Sign in",
      OrSignupwith: "Or Sign-in with",
      newToDesignSpace: "Create new account ?",
      signUpForFree: "Sign up",
      demoCredentials: "Demo Credentials:",
      useDemo: "Use Demo",
      emailAddress: "Email address",
      password: "Password",
      show: "Show",
      hide: "Hide",
      forgotPassword: "Forgot password?",
      loggingIn: "Logging in...",

      // Forgot Password
      forgotYourPassword: "Forgot your password?",
      enterEmailForReset: "Enter your email address and we'll send you a link to reset it.",
      sendResetEmail: "Send reset email",
      sendingResetEmail: "Sending reset email...",
      backToLogin: "Back to login",

      // Password Reset Flow
      enterNewPasswordDetails: "Enter your email and new password details.",
      sendOTP: "Send OTP",
      sendingOTP: "Sending OTP...",
      verifyOTP: "Verify OTP",
      verifyingOTP: "Verifying OTP...",
      otpCode: "OTP Code",
      enterOTPSentToEmail: "Enter the 6-digit OTP code sent to your email.",
      otpRequired: "OTP code is required",
      otpInvalidLength: "OTP code must be 6 digits",
      backToPasswordReset: "Back to password reset",
      redirectingToLogin: "Redirecting to login page...",
      passwordMinLength: "Password must be at least 6 characters",
      passwordMeetsRequirements: "Password meets requirements",
      passwordsMatch: "Passwords match",

      // Reset Password
      resetYourPassword: "Reset your password",
      enterNewPasswordBelow: "Enter your new password below.",
      newPassword: "New Password",
      enterNewPassword: "Enter new password",
      confirmNewPassword: "Confirm New Password",
      confirmNewPasswordPlaceholder: "Confirm new password",
      resetPassword: "Reset password",
      resettingPassword: "Resetting password...",
      passwordsDoNotMatch: "Passwords do not match",
      passwordTooShort: "Password must be at least 6 characters",
      passwordRequirements: "Password must contain at least one uppercase letter, one lowercase letter, one number, and one special character",
      emailRequired: "Email is required",
      passwordRequired: "Password is required",
      confirmPasswordRequired: "Please confirm your new password",


      // Auth - Register
      alreadyHaveAccount: "Already have an account?",
      enterDetailsToCreate: "Enter your details to create an account.",
      username: "Username",
      enterUsername: "Enter your username",
      enterPassword: "Enter your password",
      email: "Email",
      enterEmail: "Enter your email",
      phoneNumber: "Phone Number",
      enterPhoneNumber: "Enter your phone number",
      createAccount: "Create an account",
      creatingAccount: "Creating account...",
      or: "Or",
      signInWithGoogle: "Sign in with Google",
      signInWithFacebook: "Sign in with Facebook",
      success: "Success",
      redirectingToHomepage: "Redirecting to homepage...",
      invalidEmailFormat: "Invalid Email Format",
      passwordRequirements: "Invalid Password",
      invalidPhoneNumber: "Invalid Phone Number",

      // Footer
      footerVision: "Our vision is to provide convenience and help increase your sales business.",
      about: "About",
      howItWorks: "How it works",
      featured: "Featured",
      partnership: "Partnership",
      businessRelation: "Business Relation",
      community: "Community",
      events: "Events",
      blog: "Blog",
      podcast: "Podcast",
      inviteFriend: "Invite a friend",
      socials: "Socials",
      discord: "Discord",
      instagram: "Instagram",
      twitter: "Twitter",
      facebook: "Facebook",
      allRightsReserved: "©2022 MORENT. All rights reserved",
      privacyPolicy: "Privacy & Policy",
      termsCondition: "Terms & Condition",

      // Logout
      logOut: "Log Out",
      doYouWantToLogout: "Do you want to logout?",
      yes: "Yes",

      //Time-Picker
      invalidTimeFormat: "Invalid Time Format",
      timeFormatHint: "Time Format Hint: 09:00, 10:59, 12:00",
      searchResults: "Search Results",
      clearAll: "Clear All",
      activeFilters: "Active Filters",
      // Maintenance Scheduling Modal
      "maintenanceModal.title": "Schedule Maintenance",
      "maintenanceModal.car": "Car",
      "maintenanceModal.successMessage": "Maintenance scheduled successfully!",
      "maintenanceModal.titleLabel": "Title",
      "maintenanceModal.titlePlaceholder": "e.g., Oil Change, Tire Replacement",
      "maintenanceModal.locationLabel": "Location",
      "maintenanceModal.locationPlaceholder": "e.g., ABC Auto Service Center",
      "maintenanceModal.startDateLabel": "Start Date",
      "maintenanceModal.endDateLabel": "End Date",
      "maintenanceModal.noteLabel": "Note",
      "maintenanceModal.notePlaceholder": "Additional notes or instructions...",
      "maintenanceModal.cancel": "Cancel",
      "maintenanceModal.scheduling": "Scheduling...",
      "maintenanceModal.scheduleButton": "Schedule Maintenance",
      "maintenanceModal.fillRequiredFields": "Please fill in all required fields",
      "maintenanceModal.endDateAfterStart": "End date must be after start date",
      "maintenanceModal.schedulingError": "Failed to schedule maintenance. Please try again.",
      "maintenanceModal.required": "*",
    }
  },
  vi: {
    translation: {
      // NavBar
      search: "Tìm kiếm ở đây",
      signIn: "Đăng nhập",
      signUp: "Đăng ký",
      notification: "Thông báo",
      noNotifications: "Không có thông báo",
      bookingSuccessful: "Đặt xe thành công",
      unread: "chưa đọc",
      viewAllNotifications: "Xem tất cả thông báo",
      loading: "Đang tải...",

      // Filters
      filters: "Bộ lọc",
      carName: "Tên xe",
      carNamePlaceholder: "vd. Nissan, CR-V",
      minPrice: "Giá tối thiểu",
      maxPrice: "Giá tối đa",
      fuelType: "Loại nhiên liệu",
      seats: "Số ghế",
      any: "Tất cả",
      electric: "Điện",
      hybrid: "Hybrid",
      gasoline: "Xăng",
      diesel: "Dầu",
      cancel: "Hủy",
      apply: "Áp dụng",

      // HomePage - Hero Section
      heroTitle: "Nền Tảng Tốt Nhất Cho Thuê Xe",
      heroSubtitle: "Dễ dàng thuê xe một cách an toàn và đáng tin cậy. Tất nhiên với giá cả phải chăng.",
      heroTitle2: "Cách dễ dàng để thuê xe với giá rẻ",
      heroSubtitle2: "Cung cấp dịch vụ cho thuê xe giá rẻ với tiện nghi an toàn và thoải mái.",
      rentalCar: "Thuê Xe",

      // HomePage - Search Section
      pickUp: "Nhận xe",
      dropOff: "Trả xe",
      location: "Địa điểm",
      pickYourLocation: "Chọn địa điểm của bạn",
      selectCity: "Chọn thành phố",
      hoChiMinhCity: "TP.Hồ Chí Minh",
      hanoi: "Hà Nội",
      daNang: "Đà Nẵng",
      date: "Ngày",
      selectDate: "Chọn ngày",
      today: "Hôm nay",
      tomorrow: "Ngày mai",
      nextWeek: "Tuần sau",
      time: "Giờ",
      selectTime: "Chọn giờ",
      rentalPeriod: "Thời gian thuê",
      loadingCars: "Đang tải xe...",
      errorLoadingCars: "Lỗi khi tải xe:",
      // HomePage - Car Sections
      popularCar: "Xe Phổ Biến",
      recommendationCar: "Xe Đề Xuất",
      viewAll: "Xem Tất Cả",
      rentNow: "Thuê Ngay",
      perDay: "/ngày",
      showMoreCar: "Xem thêm xe",
      car: "Xe",

      // Car Card
      manual: "Số sàn",
      automatic: "Số tự động",
      people: "Người",
      person: "chỗ",
      Gasoline: "Xăng",
      Diesel: "Dầu",
      Electric: "Điện",
      // Auth - Login
      logIn: "Đăng nhập",
      OrSignupwith: "Hoặc đăng nhập với",
      newToDesignSpace: "Tạo tài khoản mới",
      signUpForFree: "Đăng ký",
      demoCredentials: "Tài khoản Demo:",
      useDemo: "Dùng Demo",
      emailAddress: "Địa chỉ email",
      password: "Mật khẩu",
      show: "Hiện",
      hide: "Ẩn",
      forgotPassword: "Quên mật khẩu?",
      loggingIn: "Đang đăng nhập...",

      // Forgot Password
      forgotYourPassword: "Quên mật khẩu?",
      enterEmailForReset: "Nhập địa chỉ email của bạn và chúng tôi sẽ gửi liên kết đặt lại mật khẩu.",
      sendResetEmail: "Gửi email đặt lại",
      sendingResetEmail: "Đang gửi email đặt lại...",
      backToLogin: "Quay lại đăng nhập",

      // Password Reset Flow
      enterNewPasswordDetails: "Nhập email và thông tin mật khẩu mới của bạn.",
      sendOTP: "Gửi mã OTP",
      sendingOTP: "Đang gửi mã OTP...",
      verifyOTP: "Xác minh OTP",
      verifyingOTP: "Đang xác minh OTP...",
      otpCode: "Mã OTP",
      enterOTPSentToEmail: "Nhập mã OTP 6 chữ số đã được gửi đến email của bạn.",
      otpRequired: "Mã OTP là bắt buộc",
      otpInvalidLength: "Mã OTP phải có 6 chữ số",
      backToPasswordReset: "Quay lại đặt lại mật khẩu",
      redirectingToLogin: "Đang chuyển hướng đến trang đăng nhập...",
      passwordMinLength: "Mật khẩu phải có ít nhất 6 ký tự",
      passwordMeetsRequirements: "Mật khẩu đáp ứng yêu cầu",
      passwordsMatch: "Mật khẩu khớp nhau",

      // Reset Password
      resetYourPassword: "Đặt lại mật khẩu",
      enterNewPasswordBelow: "Nhập mật khẩu mới của bạn bên dưới.",
      newPassword: "Mật khẩu mới",
      enterNewPassword: "Nhập mật khẩu mới",
      confirmNewPassword: "Xác nhận mật khẩu mới",
      confirmNewPasswordPlaceholder: "Xác nhận mật khẩu mới",
      resetPassword: "Đặt lại mật khẩu",
      resettingPassword: "Đang đặt lại mật khẩu...",
      passwordsDoNotMatch: "Mật khẩu không khớp",
      passwordTooShort: "Mật khẩu phải có ít nhất 6 ký tự",
      passwordRequirements: "Mật khẩu phải chứa ít nhất một chữ hoa, một chữ thường và một số",
      emailRequired: "Email là bắt buộc",
      passwordRequired: "Mật khẩu là bắt buộc",
      confirmPasswordRequired: "Vui lòng xác nhận mật khẩu mới",
      invalidEmailFormat: "Sai format email",

      // Auth - Register
      alreadyHaveAccount: "Đã có tài khoản?",
      enterDetailsToCreate: "Nhập thông tin của bạn để tạo tài khoản.",
      username: "Tên người dùng",
      enterUsername: "Nhập tên người dùng",
      enterPassword: "Nhập mật khẩu",
      email: "Email",
      enterEmail: "Nhập email",
      phoneNumber: "Số điện thoại",
      enterPhoneNumber: "Nhập số điện thoại",
      createAccount: "Tạo tài khoản",
      creatingAccount: "Đang tạo tài khoản...",
      or: "Hoặc",
      signInWithGoogle: "Đăng nhập với Google",
      signInWithFacebook: "Đăng nhập với Facebook",
      success: "Thành công!",
      redirectingToHomepage: "Đang chuyển đến trang chủ...",
      invalidEmailFormat: "Sai format email",
      passwordRequirements: "Mật khẩu phải chứa ít nhất một chữ hoa, một chữ thường, một số và một ký tự đặc biệt",
      invalidPhoneNumber: "Số điện thoại không hợp lệ",

      // Footer
      footerVision: "Tầm nhìn của chúng tôi là mang lại sự tiện lợi và giúp tăng doanh số kinh doanh của bạn.",
      about: "Về chúng tôi",
      howItWorks: "Cách hoạt động",
      featured: "Nổi bật",
      partnership: "Đối tác",
      businessRelation: "Quan hệ kinh doanh",
      community: "Cộng đồng",
      events: "Sự kiện",
      blog: "Blog",
      podcast: "Podcast",
      inviteFriend: "Mời bạn bè",
      socials: "Mạng xã hội",
      discord: "Discord",
      instagram: "Instagram",
      twitter: "Twitter",
      facebook: "Facebook",
      allRightsReserved: "©2022 MORENT. Bảo lưu mọi quyền",
      privacyPolicy: "Chính sách bảo mật",
      termsCondition: "Điều khoản & Điều kiện",

      // Logout
      logOut: "Đăng Xuất",
      doYouWantToLogout: "Bạn có muốn đăng xuất?",
      yes: "Có",

      //Time-Picker
      invalidTimeFormat: "Định dạng thời gian không hợp lệ",
      timeFormatHint: "Gợi ý định dạng: 09:00, 10:59, 12:00",

      //The Rest
      managedByMorrent: "Xe được quản lý bởi Morrent",
      noPaymentHistory: "Không có lịch sử giao dịch",
      maintenanceCalendar: "Lịch bảo trì",

      searchResults: "Kết quả tìm kiếm",
      clearAll: "Xóa tất cả",
      activeFilters: "Bộ lọc đang hoạt động",
      // Maintenance Scheduling Modal
      "maintenanceModal.title": "Lên lịch bảo dưỡng",
      "maintenanceModal.car": "Xe",
      "maintenanceModal.successMessage": "Lên lịch bảo dưỡng thành công!",
      "maintenanceModal.titleLabel": "Tiêu đề",
      "maintenanceModal.titlePlaceholder": "VD: Thay dầu, Thay lốp",
      "maintenanceModal.locationLabel": "Địa điểm",
      "maintenanceModal.locationPlaceholder": "VD: Trung tâm dịch vụ ABC",
      "maintenanceModal.startDateLabel": "Ngày bắt đầu",
      "maintenanceModal.endDateLabel": "Ngày kết thúc",
      "maintenanceModal.noteLabel": "Ghi chú",
      "maintenanceModal.notePlaceholder": "Ghi chú bổ sung hoặc hướng dẫn...",
      "maintenanceModal.cancel": "Hủy",
      "maintenanceModal.scheduling": "Đang lên lịch...",
      "maintenanceModal.scheduleButton": "Lên lịch bảo dưỡng",
      "maintenanceModal.fillRequiredFields": "Vui lòng điền tất cả các trường bắt buộc",
      "maintenanceModal.endDateAfterStart": "Ngày kết thúc phải sau ngày bắt đầu",
      "maintenanceModal.schedulingError": "Không thể lên lịch bảo dưỡng. Vui lòng thử lại.",
      "maintenanceModal.required": "*",

    }
  }
};