// Owner feature specific translations
export const inquiriesTranslate = {
  en: {
    translation: {
      // Inquiries Component
      "inquiries.title": "Inquiries",
      "inquiries.subtitle": "Receive inquiries and send responses to customers",
      "inquiries.exportReport": "Export Report",
      "inquiries.totalInquiries": "Total Inquiries",
      "inquiries.pending": "Pending",
      "inquiries.responded": "Responded",
      "inquiries.highPriority": "High Priority",
      "inquiries.searchPlaceholder": "Search by customer, subject or inquiry code",
      "inquiries.allStatuses": "All Statuses",
      "inquiries.closed": "Closed",
      "inquiries.showingResults": "Showing {{filtered}} of {{total}} inquiries",
      "inquiries.inquiryCode": "Inquiry Code",
      "inquiries.customer": "Customer",
      "inquiries.subject": "Subject",
      "inquiries.car": "Car",
      "inquiries.date": "Date",
      "inquiries.priority": "Priority",
      "inquiries.status": "Status",
      "inquiries.actions": "Actions",
      "inquiries.respond": "Respond",
      "inquiries.view": "View",
      "inquiries.close": "Close",
      "inquiries.previous": "Previous",
      "inquiries.next": "Next",
      "inquiries.loadingInquiries": "Loading inquiries...",
      "inquiries.errorLoadingInquiries": "Error Loading Inquiries",
      "inquiries.tryAgain": "Try Again",
      "inquiries.userNotLoggedIn": "User not logged in",
      "inquiries.cannotLoadInquiries": "Cannot load inquiry list",
      "inquiries.unknown": "Unknown",
      "inquiries.noData": "No data",
      "inquiries.inquiryDetails": "Inquiry Details",
      "inquiries.customerInformation": "Customer Information",
      "inquiries.name": "Name",
      "inquiries.email": "Email",
      "inquiries.phone": "Phone",
      "inquiries.previousResponse": "Your Previous Response",
      "inquiries.yourResponse": "Your Response",
      "inquiries.updateResponse": "Update Response",
      "inquiries.responsePlaceholder": "Write your response here...",
      "inquiries.cancel": "Cancel",
      "inquiries.sending": "Sending...",
      "inquiries.sendResponse": "Send Response",
      "inquiries.markAsClosed": "Mark as Closed",
      "inquiries.sendingResponse": "Sending response...",
      "inquiries.selectedInquiry": "Selected inquiry:",
      "inquiries.responseContent": "Response content:",
      "inquiries.currentUserId": "Current user ID:",
      "inquiries.formDataContent": "FormData content:",
      "inquiries.title": "Inquiries",
      "inquiries.content": "Content:",
      "inquiries.isOpen": "isOpen:",
      "inquiries.senderId": "Sender ID:",
      "inquiries.receiverId": "Receiver ID:",
      "inquiries.parentInquiryId": "Parent inquiry ID:",
      "inquiries.endpoint": "Endpoint:",
      "inquiries.responseSuccess": "Response sent successfully:",
      "inquiries.responseError": "Error sending response:",
      "inquiries.responseSuccessMessage": "Response sent successfully!",
      "inquiries.responseErrorMessage": "Cannot send response. Please try again.",
      "inquiries.markClosedMessage": "Mark inquiry as closed:",
      "inquiries.markClosedFeature": "Mark as closed feature will be implemented later.",
      "inquiries.priorityHigh": "High",
      "inquiries.priorityMedium": "Medium",
      "inquiries.priorityLow": "Low",
      "inquiries.statusPending": "Pending",
      "inquiries.statusResponded": "Responded",
      "inquiries.statusClosed": "Closed",
    }
  },
  vi: {
    translation: {
      // Inquiries Component
      "inquiries.title": "Câu Hỏi",
      "inquiries.subtitle": "Nhận câu hỏi và gửi phản hồi cho khách hàng",
      "inquiries.exportReport": "Xuất Báo Cáo",
      "inquiries.totalInquiries": "Tổng Câu Hỏi",
      "inquiries.pending": "Chờ Xử Lý",
      "inquiries.responded": "Đã Phản Hồi",
      "inquiries.highPriority": "Ưu Tiên Cao",
      "inquiries.searchPlaceholder": "Tìm kiếm theo khách hàng, chủ đề hoặc mã câu hỏi",
      "inquiries.allStatuses": "Tất Cả Trạng Thái",
      "inquiries.closed": "Đã Đóng",
      "inquiries.showingResults": "Hiển thị {{filtered}} trong tổng số {{total}} câu hỏi",
      "inquiries.inquiryCode": "Mã Câu Hỏi",
      "inquiries.customer": "Khách Hàng",
      "inquiries.subject": "Chủ Đề",
      "inquiries.car": "Xe",
      "inquiries.date": "Ngày",
      "inquiries.priority": "Ưu Tiên",
      "inquiries.status": "Trạng Thái",
      "inquiries.actions": "Hành Động",
      "inquiries.respond": "Phản Hồi",
      "inquiries.view": "Xem",
      "inquiries.close": "Đóng",
      "inquiries.previous": "Trước",
      "inquiries.next": "Sau",
      "inquiries.loadingInquiries": "Đang tải câu hỏi...",
      "inquiries.errorLoadingInquiries": "Lỗi Tải Câu Hỏi",
      "inquiries.tryAgain": "Thử Lại",
      "inquiries.userNotLoggedIn": "Người dùng chưa đăng nhập",
      "inquiries.cannotLoadInquiries": "Không thể tải danh sách câu hỏi",
      "inquiries.unknown": "Không xác định",
      "inquiries.noData": "Không có",
      "inquiries.inquiryDetails": "Chi Tiết Câu Hỏi",
      "inquiries.customerInformation": "Thông Tin Khách Hàng",
      "inquiries.name": "Tên",
      "inquiries.email": "Email",
      "inquiries.phone": "Điện Thoại",
      "inquiries.previousResponse": "Phản Hồi Trước Đó Của Bạn",
      "inquiries.yourResponse": "Phản Hồi Của Bạn",
      "inquiries.updateResponse": "Cập Nhật Phản Hồi",
      "inquiries.responsePlaceholder": "Viết phản hồi của bạn tại đây...",
      "inquiries.cancel": "Hủy",
      "inquiries.sending": "Đang gửi...",
      "inquiries.sendResponse": "Gửi Phản Hồi",
      "inquiries.markAsClosed": "Đánh Dấu Đã Đóng",
      "inquiries.sendingResponse": "Đang gửi phản hồi...",
      "inquiries.selectedInquiry": "Câu hỏi được chọn:",
      "inquiries.responseContent": "Nội dung phản hồi:",
      "inquiries.currentUserId": "ID người dùng hiện tại:",
      "inquiries.formDataContent": "Nội dung FormData:",
      "inquiries.title": "Tiêu đề:",
      "inquiries.content": "Nội dung:",
      "inquiries.isOpen": "isOpen:",
      "inquiries.senderId": "ID người gửi:",
      "inquiries.receiverId": "ID người nhận:",
      "inquiries.parentInquiryId": "ID câu hỏi gốc:",
      "inquiries.endpoint": "Endpoint:",
      "inquiries.responseSuccess": "Gửi phản hồi thành công:",
      "inquiries.responseError": "Lỗi khi gửi phản hồi:",
      "inquiries.responseSuccessMessage": "Gửi phản hồi thành công!",
      "inquiries.responseErrorMessage": "Không thể gửi phản hồi. Vui lòng thử lại.",
      "inquiries.markClosedMessage": "Đánh dấu câu hỏi đã đóng:",
      "inquiries.markClosedFeature": "Tính năng đánh dấu đã đóng sẽ được triển khai sau.",
      "inquiries.priorityHigh": "Cao",
      "inquiries.priorityMedium": "Trung bình",
      "inquiries.priorityLow": "Thấp",
      "inquiries.statusPending": "Chờ xử lý",
      "inquiries.statusResponded": "Đã phản hồi",
      "inquiries.statusClosed": "Đã đóng",

    }
  }
};