export const userTranslate = {
  en: {
    translation: {
      // Profile - Update Email Dialog
      updateEmail: "Update Email",
      newEmail: "New Email",

      // Profile - Favourite Car Page
      favouriteCar: "Favourite Car",
      noFavouriteCars: "No Favourite Cars",
      noFavouriteCarsMessage: "You haven't added any cars to your favorites yet.",
      browseCars: "Browse Cars",
      addToFavorites: "Add to Favorites",
      removeFromFavorites: "Remove from Favorites",

      // Profile - Help Center Page
      helpCenterDescription: "Find answers, get support, and learn how to use the app.",
      accountAndProfile: "Account & Profile",
      accountAndProfileDescription: "Update account info, password, and preferences.",
      bookingAndRentals: "Booking & Rentals",
      bookingAndRentalsDescription: "Create bookings, manage trips, and payments.",
      troubleshooting: "Troubleshooting",
      troubleshootingDescription: "Fix common issues and contact support.",
      stillNeedHelp: "Still need help?",
      contactSupport: "Contact support",
      openTicket: "Open a ticket",

      // Profile - Inbox Page
      markAllAsRead: "Mark all as read",
      searchMessages: "Search messages...",
      allTags: "All tags",
      bookingTag: "Booking",
      billingTag: "Billing",
      promoTag: "Promo",
      systemTag: "System",
      onlyUnread: "Only unread",
      noMessagesFound: "No messages found.",
      markUnread: "Mark unread",
      markRead: "Mark read",
      delete: "Delete",
      page: "Page",
      deleteMessage: "Delete message",
      deleteMessageConfirm: "Delete",
      // Profile - My Profile Page
      accountInformation: "Account Information",
      save: "Save",
      dateOfBirth: "Date of Birth",
      gender: "Gender",
      male: "Male",
      female: "Female",
      other: "Other",
      addPhoneNumber: "Add Phone Number",
      enterAddress: "Enter address",
      address: "Address",
      google: "Google",
      connected: "Connected",
      addLink: "Add link",
      enterFullName: "Full Name",
      noLicenseUploaded: "No License Uploaded",
      uploadlicensepending: "Waiting for approved",
      uploadlicenseapproved: "Approved",
      uploadlicensedenied: "Denied",
      // Profile - Reimburse Page
      totalSubmitted: "Total Submitted",
      submitReimbursement: "Submit a reimbursement",
      history: "History",
      searchRefOrNotes: "Search ref or notes",
      all: "All",
      ref: "Ref",
      category: "Category",
      note: "Note",
      noRequestsFound: "No requests found.",
      fuel: "Fuel",
      toll: "Toll",
      parking: "Parking",
      optionalDetails: "Optional details",
      reset: "Reset",
      submit: "Submit",

      // Profile - Rental History Page
      type: "Type",
      brand: "Brand",
      plateNo: "Plate No",
      rentDay: "Rent Day",
      paymentDate: "Payment Date",
      noPayment: "No Payment",
      noRentalHistory: "No Rental History",
      // Profile - Settings Page
      security: "Security",
      securityDescription: "Manage account security and verification settings.",
      newPassword: "New password",
      confirmPassword: "Confirm password",
      updatePassword: "Update password",
      emailVerificationStatus: "Email Verification Status",
      unverified: "Unverified",
      verifyEmailDescription: "Verify your email to enhance account security and receive important notifications.",
      sendVerificationEmail: "Send verification email",

      // Profile - Sidebar
      myProfile: "My Profile",
      "Rental History": "Rental History",
      favouriteCars: "Favourite Cars",

      // Upload Driver License
      updateDriverLicense: "Update Driver's License",
      uploadDriverLicenseDescription: "Upload a clear photo or scan of your driver's license. Accepted formats: JPG, PNG,(max 5MB)",
      invalidDriverLicenseFileType: "Please upload a valid image (JPG, PNG)",
      driverLicenseUploadedSuccessfully: "Driver's license uploaded successfully!",
      pleaseSelectFileFirst: "Please select a file first",
      failedToUploadDriverLicense: "Failed to upload driver's license. Please try again.",
      driverLicenseFormatsAccepted: "JPG, PNG (max 5MB)",
      uploadDriverLicenseButton: "Upload Driver's License",
      driverLicenseTip1: "Ensure all text on the license is clearly visible",
      driverLicenseTip2: "The license must be valid and not expired",
      driverLicenseTip3: "Both front and back may be required",
      driverLicenseTip4: "Your information will be kept secure and confidential",
      editLicense: "Edit",
      cancelEdit: "Cancell",
      frontDriverLicense: "Front Driver License",
      backDriverLicense: "Back Driver License",
      invalidImg: "Please upload a photo of your valid driver's license."
    }
  },
  vi: {
    translation: {
      // Profile - Update Email Dialog
      updateEmail: "Cập nhật Email",
      newEmail: "Email mới",

      // Profile - Favourite Car Page
      favouriteCar: "Xe Yêu Thích",
      noFavouriteCars: "Không Có Xe Yêu Thích",
      noFavouriteCarsMessage: "Bạn chưa thêm xe nào vào danh sách yêu thích.",
      browseCars: "Duyệt Xe",
      addToFavorites: "Thêm vào Yêu Thích",
      removeFromFavorites: "Xóa khỏi Yêu Thích",

      // Profile - Help Center Page
      helpCenterDescription: "Tìm câu trả lời, nhận hỗ trợ và học cách sử dụng ứng dụng.",
      accountAndProfile: "Tài khoản & Hồ sơ",
      accountAndProfileDescription: "Cập nhật thông tin tài khoản, mật khẩu và tùy chọn.",
      bookingAndRentals: "Đặt xe & Thuê xe",
      bookingAndRentalsDescription: "Tạo đặt xe, quản lý chuyến đi và thanh toán.",
      troubleshooting: "Khắc phục sự cố",
      troubleshootingDescription: "Khắc phục các vấn đề thường gặp và liên hệ hỗ trợ.",
      stillNeedHelp: "Vẫn cần trợ giúp?",
      contactSupport: "Liên hệ hỗ trợ",
      openTicket: "Mở phiếu yêu cầu",

      // Profile - Inbox Page
      markAllAsRead: "Đánh dấu tất cả đã đọc",
      searchMessages: "Tìm kiếm tin nhắn...",
      allTags: "Tất cả thẻ",
      bookingTag: "Đặt xe",
      billingTag: "Thanh toán",
      promoTag: "Khuyến mãi",
      systemTag: "Hệ thống",
      onlyUnread: "Chỉ chưa đọc",
      noMessagesFound: "Không tìm thấy tin nhắn.",
      markUnread: "Đánh dấu chưa đọc",
      markRead: "Đánh dấu đã đọc",
      delete: "Xóa",
      page: "Trang",
      deleteMessage: "Xóa tin nhắn",
      deleteMessageConfirm: "Xóa",

      // Profile - My Profile Page
      accountInformation: "Thông tin tài khoản",
      save: "Lưu",
      dateOfBirth: "Ngày sinh",
      gender: "Giới tính",
      male: "Nam",
      female: "Nữ",
      other: "Khác",
      addPhoneNumber: "Thêm số điện thoại",
      enterAddress: "Nhập địa chỉ",
      address: "Địa chỉ",
      google: "Google",
      connected: "Đã kết nối",
      addLink: "Thêm liên kết",
      enterFullName: "Họ và Tên",
      noLicenseUploaded: "Chưa cập nhập bằng lái xe",
      uploadlicensepending: "Chờ xác thực",
      uploadlicenseapproved: "Đã xác thực",
      uploadlicensedenied: "Xác thực thất bại",
      // Profile - Reimburse Page
      totalSubmitted: "Tổng đã gửi",
      submitReimbursement: "Gửi yêu cầu hoàn tiền",
      history: "Lịch sử",
      searchRefOrNotes: "Tìm kiếm mã hoặc ghi chú",
      all: "Tất cả",
      ref: "Mã",
      category: "Danh mục",
      note: "Ghi chú",
      noRequestsFound: "Không tìm thấy yêu cầu.",
      fuel: "Nhiên liệu",
      toll: "Phí cầu đường",
      parking: "Đỗ xe",
      optionalDetails: "Chi tiết tùy chọn",
      reset: "Đặt lại",
      submit: "Gửi",

      // Profile - Rental History Page
      type: "Loại",
      brand: "Thương hiệu",
      plateNo: "Biển số",
      rentDay: "Ngày thuê",
      paymentDate: "Ngày thanh toán",
      noPayment: "Chưa thanh toán",
      noRentalHistory: "Không có lịch sử thuê xe",
      // Profile - Settings Page
      security: "Bảo mật",
      securityDescription: "Quản lý bảo mật tài khoản và cài đặt xác minh.",
      newPassword: "Mật khẩu mới",
      confirmPassword: "Xác nhận mật khẩu",
      updatePassword: "Cập nhật mật khẩu",
      emailVerificationStatus: "Trạng thái xác minh email",
      unverified: "Chưa xác minh",
      verifyEmailDescription: "Xác minh email của bạn để tăng cường bảo mật tài khoản và nhận thông báo quan trọng.",
      sendVerificationEmail: "Gửi email xác minh",

      // Profile - Sidebar
      myProfile: "Hồ Sơ Của Tôi",
      "Rental History": "Lịch Sử Thuê Xe",
      favouriteCars: "Xe Yêu Thích",

      // Upload Driver License
      updateDriverLicense: "Cập Nhật Giấy Phép Lái Xe",
      uploadDriverLicenseDescription: "Tải lên ảnh hoặc bản scan rõ ràng giấy phép lái xe của bạn. Định dạng chấp nhận: JPG, PNG, (tối đa 5MB)",
      invalidDriverLicenseFileType: "Vui lòng tải lên ảnh hợp lệ (JPG, PNG)",
      driverLicenseUploadedSuccessfully: "Tải giấy phép lái xe lên thành công!",
      pleaseSelectFileFirst: "Vui lòng chọn tệp trước",
      failedToUploadDriverLicense: "Không thể tải giấy phép lái xe lên. Vui lòng thử lại.",
      driverLicenseFormatsAccepted: "JPG, PNG (tối đa 5MB)",
      uploadDriverLicenseButton: "Tải Lên Giấy Phép Lái Xe",
      driverLicenseTip1: "Đảm bảo tất cả văn bản trên giấy phép đều rõ ràng",
      driverLicenseTip2: "Giấy phép phải còn hiệu lực và chưa hết hạn",
      driverLicenseTip3: "Có thể yêu cầu cả mặt trước và mặt sau",
      driverLicenseTip4: "Thông tin của bạn sẽ được bảo mật và an toàn",
      editLicense: "Cập nhập",
      cancelEdit: "Hủy",
      frontDriverLicense: "Mặt trước",
      backDriverLicense: "Mặt sau",
      invalidImg: "Vui lòng tải ảnh bằng lái hợp lệ",
      //InboxPage
      messageDetails: "Thông báo",
      messageInformation: "Thông tin người gửi",
      dateInbox: "Ngày gửi",
      fromInbox: "Gửi từ",
      noConversationHistory: "Không có lịch sử chat",
      conversationHistory: "Lịch sử chat",
    }
  }
};