// Booking Management feature specific translations
export const bookingManagementTranslations = {
  en: {
    translation: {
      // Booking Management Component
      "bookingManagement.title": "Booking Management",
      "bookingManagement.subtitle": "Handle vehicle pickup and return for active bookings",
      "bookingManagement.exportReport": "Export Report",
      "bookingManagement.searchPlaceholder": "Search by booking ID, customer or vehicle",
      "bookingManagement.allStatuses": "All Statuses",
      "bookingManagement.confirmed": "Confirmed",
      "bookingManagement.checkedIn": "Checked In",
      "bookingManagement.checkedOut": "Checked Out",
      "bookingManagement.completed": "Completed",
      "bookingManagement.showingResults": "Showing {{filtered}} of {{total}} bookings",
      "bookingManagement.bookingId": "Booking ID",
      "bookingManagement.vehicleInfo": "Vehicle Information",
      "bookingManagement.customer": "Customer",
      "bookingManagement.rentalPeriod": "Rental Period",
      "bookingManagement.pickupReturnTime": "Pickup/Return Time",
      "bookingManagement.status": "Status",
      "bookingManagement.pickup": "Pickup",
      "bookingManagement.return": "Return",
      "bookingManagement.to": "to",
      "bookingManagement.today": "Today",
      "bookingManagement.loadingBookings": "Loading booking data...",
      "bookingManagement.errorLoadingBookings": "Unable to load booking data",
      "bookingManagement.tryAgain": "Try Again",
      "bookingManagement.confirmedStatus": "Confirmed",
      "bookingManagement.completedStatus": "Completed",
      "bookingManagement.cancelledStatus": "Cancelled",
      "bookingManagement.pendingStatus": "Pending",
      "bookingManagement.pending": "Pending",
      "bookingManagement.pickedUp": "Picked up",
      "bookingManagement.returned": "Returned",
      "bookingManagement.unknownCar": "Unknown Car",
      "bookingManagement.unknownCustomer": "Unknown Customer",
      "bookingManagement.notAvailable": "N/A",
    }
  },
  vi: {
    translation: {
      // Booking Management Component
      "bookingManagement.title": "Quản lý đặt xe",
      "bookingManagement.subtitle": "Xử lý việc nhận xe và trả xe cho các đặt xe đang hoạt động",
      "bookingManagement.exportReport": "Xuất báo cáo",
      "bookingManagement.searchPlaceholder": "Tìm kiếm theo mã đặt xe, khách hàng hoặc xe",
      "bookingManagement.allStatuses": "Tất cả trạng thái",
      "bookingManagement.confirmed": "Đã xác nhận",
      "bookingManagement.pending": "Đang chờ",
      "bookingManagement.checkedIn": "Đã nhận xe",
      "bookingManagement.checkedOut": "Đã trả xe",
      "bookingManagement.completed": "Hoàn thành",
      "bookingManagement.showingResults": "Hiển thị {{filtered}} trong tổng số {{total}} đặt xe",
      "bookingManagement.bookingId": "Mã đặt xe",
      "bookingManagement.vehicleInfo": "Thông tin xe",
      "bookingManagement.customer": "Khách hàng",
      "bookingManagement.rentalPeriod": "Thời gian thuê",
      "bookingManagement.pickupReturnTime": "Thời gian nhận/trả xe",
      "bookingManagement.status": "Trạng thái",
      "bookingManagement.pickup": "Nhận xe",
      "bookingManagement.return": "Trả xe",
      "bookingManagement.to": "đến",
      "bookingManagement.today": "Hôm nay",
      "bookingManagement.loadingBookings": "Đang tải dữ liệu đặt xe...",
      "bookingManagement.errorLoadingBookings": "Không thể tải dữ liệu đặt xe",
      "bookingManagement.tryAgain": "Thử lại",
      "bookingManagement.confirmedStatus": "Đã xác nhận",
      "bookingManagement.completedStatus": "Hoàn thành",
      "bookingManagement.cancelledStatus": "Đã hủy",
      "bookingManagement.pendingStatus": "Đang chờ xác nhận",
      "bookingManagement.pickedUp": "Đã nhận xe",
      "bookingManagement.returned": "Đã trả xe",
      "bookingManagement.unknownCar": "Xe không xác định",
      "bookingManagement.unknownCustomer": "Khách hàng không xác định",
      "bookingManagement.notAvailable": "Không có",
    }
  }
};