export const ownerTranslate = {
  en: {
    translation: {
      // Register Car
      registerCar: "Register Car",
      return: "Return",
      licensePlateNumber: "License Plate Number",
      licensePlateRequired: "*Car License Plate Number is required for registration",
      enterLicensePlate: "Enter license plate number",
      basicInformation: "Basic Information",
      basicInfoRequired: "*Basic information is required for registration",
      model: "Model",
      unspecified: "Unspecified",
      civic: "Civic",
      accord: "Accord",
      crv: "CR-V",
      numberOfSeat: "Number of Seat",
      yearOfManufacture: "Year of Manufacture",
      transmission: "Transmission",
      fuelConsumption: "Fuel consumption",
      fuelConsumptionDescription: "Number of liters of fuel for 100km",
      enterFuelConsumption: "Enter fuel consumption",
      describe: "Describe",
      describeYourCar: "Describe your car...",
      defaultRentalPrice: "Default rental price",
      defaultRentalPriceDescription: "Set the price for renting out your car to help customers easily choose the right car. You can change the price later.",
      vehicleAddress: "Vehicle address",
      enterVehicleAddress: "Enter vehicle address",
      rentalTerms: "Rental Terms",
      rentalTermsDescription: "State the requirements for the customer to rent the car",
      enterRentalTerms: "Enter rental terms and conditions...",
      photos: "Photos",
      photosDescription: "Select high-quality photos from different angles to attract customers.",
      upload: "Upload",
      toyota: "Toyota",
      bmw: "BMW",
      mercedes: "Mercedes",
      audi: "Audi",
      honda: "Honda",
      consumption: "Consumption",
      // Owner Dashboard
      ownerDashboard: "Owner Dashboard",
      ownerDashboardTitle: "Owner Dashboard",
      maintenanceCard: "Maintenance",
      maintenanceDescription: "Track upcoming maintenance schedules and receive notifications.",
      usageAndMileageCard: "Usage & Mileage",
      usageAndMileageDescription: "Monitor mileage and usage statistics by vehicle.",
      rentalActivityCard: "Rental Activity",
      rentalActivityDescription: "View recent bookings and history.",

      // Owner Layout - Sidebar
      ownerMenu: "OWNER MENU",
      maintenanceSchedule: "Maintenance Schedule",
      usageAndMileage: "Usage",
      rentalHistory: "Rental History",
      customerFeedback: "Customer Feedback",
      inquiries: "Inquiries",
      bookingsPickupReturn: "Bookings",
      payments: "Payments",
      registerNewCar: "Register New Car",
      registerNewCarSection: "Register New Car",
      maintenanceCalendar: "Maintenance Calendar",
      submitVehicleRegistrationCertificate: "Submit Vehicle Registration Certificate",

      // Register Car Step 3 - Photo Upload
      clickToUpload: "Click to upload",
      orDragAndDrop: "or drag and drop",
      imageFormatsAccepted: "JPG, PNG, JIFF (max 5MB per file)",
      photosUploadedSuccessfully: "Photos uploaded successfully!",
      pleaseUploadAtLeastOnePhoto: "Please upload at least one photo",
      failedToUploadPhotos: "Failed to upload photos. Please try again.",
      invalidFileType: "Please upload valid image files (JPG, PNG, JIFF)",
      fileSizeTooLarge: "File size must be less than 5MB",
      maxFilesReached: "Maximum {{max}} files allowed",
      uploading: "Uploading...",
      completeRegistration: "Complete Registration",
      importantInformation: "Important Information",
      photoTip1: "Upload high-quality photos from different angles",
      photoTip2: "Include front, back, side, and interior views",
      photoTip3: "Ensure good lighting and clear visibility",
      photoTip4: "At least 3-5 photos recommended for better visibility",
      remove: "Remove",
      uploadComplete: "Upload complete",
      uploadCancelled: "Upload cancelled",
      uploadError: "Error during upload",
      tapToCancel: "Tap to cancel",
      tapToRetry: "Tap to retry",
      tapToUndo: "Tap to undo",
      retry: "Retry",
      undo: "Undo",
      maps:"Map",

      //The Rest II
      paymentHistory: "Payment History",
      totalRevenue: "Total Revenue",
      newCarBookingRequest: "New Car Booking Request",
      vehiclesCurrentlyRented: "Vehicles Currently Rented",
      vehiclesAvailable: "Vehicles Available",
      paymentSummary: "Payment Summary",
      totalReceived: "Total Received",
      bookingFee: "Booking Fee",
      rentalFee: "Rental Fee",
      paymentPending: "Payment Pending",
      recentBookings: "Recent Bookings",
      bookingCode: "Booking Code",
      customer: "Customer",
      rentalDuration: "Rental Duration",
      pickUpTime: "Pick-up Time",
      returnTime: "Return Time",
      days: "Days",
      viewAll: "View All",
      vehicleStatusSummary: "Vehicle Status Summary",
      available: "Available",
      inactive: "Inactive",
      underMaintenance: "Under Maintenance",
      booked: "Booked",
      pending: "Pending",
      registrationStatus: "Registration Status",
      approved: "Approved",
      pendingApproval: "Pending Approval",
      rejected: "Rejected",
      denied: "Denied",
      noUpload: "No Upload",
      bookingStatus: "Booking Status",
      topCarCarrier: "Top Car Manufactures",
      bookingOverview: "Booking Overview",
      last7Days: "Last 7 Days",
      // Owner Dashboard specific translations
      newCarBookingRequest: "Total Completed Booking",
      vehiclesCurrentlyRented: "Vehicles Currently Rented",
      vehiclesAvailable: "Vehicles Available",
      paymentSummary: "Payment Summary",
      totalReceived: "Total Received",
      bookingFee: "Booking Fee",
      rentalFee: "Rental Fee",
      paymentPending: "Payment Pending",
      recentBookings: "Recent Bookings",
      bookingCode: "Booking Code",
      customer: "Customer",
      rentalDuration: "Rental Duration",
      pickUpTime: "Pick-up Time",
      returnTime: "Return Time",
      days: "days",
      viewAll: "View All",
      vehicleStatusSummary: "Vehicle Status Summary",
      available: "Available",
      underMaintenance: "Under Maintenance",
      booked: "Booked",
      pending: "Pending",
      registrationStatus: "Registration Status",
      approved: "Approved",
      pendingApproval: "Pending Approval",
      rejected: "Rejected",
      topCarManufacturers: "Top Car Manufacturers",
      ownerDashboardOverview: "Overview of car rental business",
      loadingDashboard: "Loading dashboard...",
      carStatusSummary: "Car Status Summary",
      registrationDocumentStatus: "Registration Document Status",
      bookingStatusDistribution: "Booking Status",
      topManufacturersConfirmedCompleted: "Top Car Manufacturers (Confirmed/Completed Bookings)",
      noConfirmedCompletedBookings: "No confirmed or completed bookings yet",
      noBookingData: "No booking data",
      bookingsText: "bookings",
      // Booking status chart labels
      pendingBookings: "Pending",
      confirmedBookings: "Confirmed",
      completedBookings: "Completed",
      cancelledBookings: "Cancelled",
      searchMaintenance:"Search maintenance schedule by license"
    }
  },
  vi: {
    translation: {
      // Register Car
      registerCar: "Đăng Ký Xe",
      return: "Quay lại",
      licensePlateNumber: "Biển Số Xe",
      licensePlateRequired: "*Biển số xe là bắt buộc để đăng ký",
      enterLicensePlate: "Nhập biển số xe",
      basicInformation: "Thông Tin Cơ Bản",
      basicInfoRequired: "*Thông tin cơ bản là bắt buộc để đăng ký",
      model: "Mẫu xe",
      unspecified: "Không xác định",
      civic: "Civic",
      accord: "Accord",
      crv: "CR-V",
      numberOfSeat: "Số Ghế",
      yearOfManufacture: "Năm Sản Xuất",
      transmission: "Hộp Số",
      fuelConsumption: "Mức Tiêu Thụ Nhiên Liệu",
      fuelConsumptionDescription: "Số lít nhiên liệu cho 100km",
      enterFuelConsumption: "Nhập mức tiêu thụ nhiên liệu",
      describe: "Mô Tả",
      describeYourCar: "Mô tả xe của bạn...",
      defaultRentalPrice: "Giá Thuê Mặc Định",
      defaultRentalPriceDescription: "Đặt giá cho thuê xe của bạn để giúp khách hàng dễ dàng chọn xe phù hợp. Bạn có thể thay đổi giá sau.",
      vehicleAddress: "Địa Chỉ Xe",
      enterVehicleAddress: "Nhập địa chỉ xe",
      rentalTerms: "Điều Khoản Thuê Xe",
      rentalTermsDescription: "Nêu các yêu cầu để khách hàng thuê xe",
      enterRentalTerms: "Nhập điều khoản và điều kiện thuê xe...",
      photos: "Hình Ảnh",
      photosDescription: "Chọn ảnh chất lượng cao từ nhiều góc độ để thu hút khách hàng.",
      upload: "Tải lên",
      toyota: "Toyota",
      bmw: "BMW",
      mercedes: "Mercedes",
      audi: "Audi",
      honda: "Honda",
      consumption: "Tiêu hao",
      // Owner Dashboard
      ownerDashboard: "Bảng Điều Khiển Chủ Xe",
      ownerDashboardTitle: "Bảng Điều Khiển Chủ Xe",
      maintenanceCard: "Bảo Trì",
      maintenanceDescription: "Theo dõi lịch bảo trì sắp tới và nhận thông báo.",
      usageAndMileageCard: "Sử Dụng & Số Km",
      usageAndMileageDescription: "Giám sát số km và thống kê sử dụng theo xe.",
      rentalActivityCard: "Hoạt Động Cho Thuê",
      rentalActivityDescription: "Xem các đặt chỗ gần đây và lịch sử.",

      // Owner Layout - Sidebar
      ownerMenu: "Menu quản lý xe",
      maintenanceSchedule: "Lịch Bảo Trì",
      usageAndMileage: "Mức sử dụng",
      rentalHistory: "Lịch Sử Cho Thuê",
      customerFeedback: "Phản Hồi Khách Hàng",
      inquiries: "Yêu Cầu",
      bookingsPickupReturn: "Đặt Chỗ (Nhận/Trả Xe)",
      payments: "Thanh Toán",
      registerNewCar: "Đăng Ký Xe Mới",
      registerNewCarSection: "Đăng Ký Xe Mới",
      submitVehicleRegistrationCertificate: "Nộp giấy đăng kiểm",
      // Register Car Step 3 - Photo Upload
      clickToUpload: "Nhấp để tải lên",
      orDragAndDrop: "hoặc kéo và thả",
      imageFormatsAccepted: "JPG, PNG, JIFF (tối đa 5MB mỗi tệp)",
      photosUploadedSuccessfully: "Tải ảnh lên thành công!",
      pleaseUploadAtLeastOnePhoto: "Vui lòng tải lên ít nhất một ảnh",
      failedToUploadPhotos: "Không thể tải ảnh lên. Vui lòng thử lại.",
      invalidFileType: "Vui lòng tải lên tệp ảnh hợp lệ (JPG, PNG, JIFF)",
      fileSizeTooLarge: "Kích thước tệp phải nhỏ hơn 5MB",
      maxFilesReached: "Tối đa {{max}} tệp được phép",
      uploading: "Đang tải lên...",
      completeRegistration: "Hoàn Tất Đăng Ký",
      importantInformation: "Thông Tin Quan Trọng",
      photoTip1: "Tải lên ảnh chất lượng cao từ nhiều góc độ",
      photoTip2: "Bao gồm góc nhìn phía trước, phía sau, bên cạnh và nội thất",
      photoTip3: "Đảm bảo ánh sáng tốt và hình ảnh rõ ràng",
      photoTip4: "Nên có ít nhất 3-5 ảnh để tăng khả năng hiển thị",
      remove: "Xóa",
      uploadComplete: "Tải lên hoàn tất",
      uploadCancelled: "Đã hủy tải lên",
      uploadError: "Lỗi khi tải lên",
      tapToCancel: "Nhấn để hủy",
      tapToRetry: "Nhấn để thử lại",
      tapToUndo: "Nhấn để hoàn tác",
      retry: "Thử lại",
      undo: "Hoàn tác",

      // Owner Dashboard specific translations
      ownerDashboardOverview: "Tổng quan về quản lý cho thuê xe",
      loadingDashboard: "Đang tải bảng điều khiển...",
      carStatusSummary: "Tóm tắt trạng thái xe",
      registrationDocumentStatus: "Trạng thái giấy đăng ký",
      bookingStatusDistribution: "Trạng thái đặt xe",
      topManufacturersConfirmedCompleted: "Hãng xe hàng đầu (Đặt xe đã xác nhận/hoàn thành)",
      noConfirmedCompletedBookings: "Chưa có đặt xe nào được xác nhận hoặc hoàn thành",
      noBookingData: "Không có dữ liệu đặt phòng",
      bookingsText: "đặt phòng",
      maps:"Bản đồ",
      searchMaintenance:"Tìm lịch bảo trì với biển số xe",

      //The Rest II
      paymentHistory: "Lịch sử giao dịch",
      totalRevenue: "Tổng doanh thu",
      newCarBookingRequest: "Số yêu cầu đặt xe đã hoàn thành",
      vehiclesCurrentlyRented: "Xe đang được thuê",
      vehiclesAvailable: "Xe có sẵn",
      paymentSummary: "Tóm tắt thanh toán",
      totalReceived: "Tổng đã nhận",
      bookingFee: "Phí đặt xe",
      rentalFee: "Phí thuê xe",
      paymentPending: "Thanh toán đang chờ",
      recentBookings: "Đặt xe gần đây",
      bookingCode: "Mã đặt xe",
      customer: "Khách hàng",
      rentalDuration: "Thời gian thuê",
      pickUpTime: "Thời gian nhận xe",
      returnTime: "Thời gian trả xe",
      days: "ngày",
      viewAll: "Xem tất cả",
      vehicleStatusSummary: "Tóm tắt trạng thái xe",
      available: "Có sẵn",
      inactive: "Không hoạt động",
      underMaintenance: "Đang bảo trì",
      booked: "Đã đặt",
      pending: "Chờ xử lý",
      registrationStatus: "Trạng thái đăng ký",
      approved: "Đã duyệt",
      pendingApproval: "Chờ duyệt",
      rejected: "Bị từ chối",
      bookingStatus: "Trạng thái đặt xe",
      topCarManufacturers: "Hãng xe hàng đầu",
      bookingOverview: "Tổng quan đặt xe",
      last7Days: "7 ngày qua",

      // Booking status chart labels
      pendingBookings: "Chờ xử lý",
      confirmedBookings: "Đã xác nhận",
      completedBookings: "Hoàn thành",
      cancelledBookings: "Đã hủy",
      vehiclesCurrentlyRented: "Xe đang cho thuê",
      vehiclesAvailable: "Xe có sẵn",
      paymentSummary: "Tóm tắt thanh toán",
      paymentsPending: "Thanh toán chờ xử lý",
      totalReceived: "Tổng đã nhận",
      bookingFee: "Phí đặt xe",
      rentalFee: "Phí thuê xe",
      paymentPending: "Thanh toán chờ xử lý",
      recentBookings: "Đặt xe gần đây",
      bookingCode: "Mã đặt xe",
      customer: "Khách hàng",
      rentalDuration: "Thời gian thuê",
      pickUpTime: "Thời gian nhận xe",
      returnTime: "Thời gian trả xe",
      days: "ngày",
      viewAll: "Xem tất cả",
      vehicleStatusSummary: "Tóm tắt trạng thái xe",
      available: "Có sẵn",
      underMaintenance: "Đang bảo trì",
      booked: "Đã đặt",
      pending: "Chờ xử lý",
      registrationStatus: "Trạng thái giấy đăng ký",
      approved: "Đã duyệt",
      pendingApproval: "Chờ duyệt",
      rejected: "Bị từ chối",
      denied: "Bị từ chối",
      noUpload: "Chưa tải lên",
      bookingStatus: "Trạng thái đặt phòng",
      topCarCarrier: "Hãng xe hàng đầu (Đặt xe đã xác nhận/hoàn thành)",
      bookingOverview: "Tổng quan Booking",
      last7Days: "7 ngày qua",
    }
  }
};